### ISSUE TITLE
Write documentation for SUL microsite

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1033]
(These might be separate tickets? Need more discussion on where these different forms of documentation will reside.)

Targeted to curators and potential curators:
- [ ] How to get started building a SUL exhibit with Spotlight (how to request an exhibit, etc.)
- [ ] FAQ
- [ ] Policies related to creating SUL exhbiits

**Comment by mejackreed** [comment]
Is this still relevant @ggeisler ? I think some of this work has been done internally at Stanford, but not needed for the broader community, correct?

**Comment by ggeisler** [comment]
@mejackreed Yeah, we've done a lot of documentation on the service team so I think this ticket is more than satisfied (just forgot it existed). Closing.
