### ISSUE TITLE
Enable addition of new objects from IIIF manifest or collection

### ISSUE THREAD

**Issue by snydman** [projectblacklight/spotlight#1113]
In addition to non-repository and local repository items, we should provide an option Item administration to add objects from a known IIIF manifest or collection.  

Here is a list of IIIF collections (which contain IIIF manifests): https://github.com/ryanfb/iiif-universe/blob/gh-pages/iiif-universe.json

We have several examples of spotlight resource implementations, including:
- github.com/sul-dlss/spotlight-dor-resources
- https://github.com/jkeck/spotlight-flickr-resources
- https://github.com/cbeer/spotlight-atom

Given the push to consume and produce IIIF resources within spotlight, I suggest we should add this as another concrete resource implementation within spotlight. We can iterate on the ultimate design, but the basic flow probably goes something like:
- A curator goes to the "Items" page and clicks "Add repository item"
- The curator enters a URL to a IIIF collection or manifest
- Spotlight processes collections and indexes new documents for each manifest
- The IIIF manifest may include some key-value pairs for metadata. We should capture those. One approach we've taken before is to create new exhibit custom fields and index the data into them. This allows the curator to get immediate control over the fields, without needing blacklight configuration changes. (see https://github.com/cbeer/spotlight-atom/blob/master/app/models/spotlight/resources/atom_harvester.rb#L82-L88).
- IIIF manifests may have recommended thumbnails. If it does, we should use it. If it doesn't, we should derive a default one from the first resource in the manifest. In both cases, the URL to the thumbnail should be indexed in the appropriate thumbnail field.
- We should also index the URL to the IIIF manifest, as it should be useful for displaying the object

**Comment by snydman** [comment]
here is a manifest http://purl.stanford.edu/xd360wd1446/iiif/manifest.json

**Comment by cbeer** [comment]
On the spotlight side, this would be a good opportunity to revisit the "repository" and "non-repository" labels. "out there somewhere" and "brand new" seem to be the distinctions we're actually trying to make.

I've asked @azaroth42 to provide a IIIF collection, which I believe encompasses the full range of objects we'd like spotlight/blacklight to be able to consume

**Comment by azaroth42** [comment]
Can you make a ticket for the collections and assign to me? Will do before the end of the week when I'm back in the country

**Comment by snydman** [comment]
http://dlss-dev-azaroth.stanford.edu/prezi/colls/top.json

**Comment by cbeer** [comment]
@azaroth42 @mejackreed could you provide a sampling of manifests from some other providers?

**Comment by azaroth42** [comment]
https://github.com/ryanfb/iiif-universe/blob/gh-pages/iiif-universe.json

**Comment by cbeer** [comment]
Perfect, thanks.

**Comment by ndushay** [comment]
once loaded, these objects should look like any other non-repo objects.  e.g.  Beasts and Books coll

https://exhibits.stanford.edu/beasts/default-exhibit/catalog/1-21

however, would be cool if we could get images to use o-embed viewer.

**Comment by ndushay** [comment]
@jkeck  please vet this:

Spotlight uses blacklight-gallery, which uses openseadragon to render IIIF stuff.  

In the spotlight gem, the test catalog_controller shows a ```tile_source_field``` set to ```content_metadata_image_iiif_info_ssm``` and a partials insert set to openseadragon:

https://github.com/sul-dlss/spotlight/blob/master/spec/test_app_templates/catalog_controller.rb#L32-L33

using these for uploaded IIIF images _should_ enable spotlight to use openseadragon to display the images with full IIIF features.

**Comment by snydman** [comment]
Example of IIIF collections live, in production in the wild:

http://iiif.bodleian.ox.ac.uk/iiif/collection/Hebrew
http://iiif.bodleian.ox.ac.uk/iiif/collection/WesternManuscripts

**Comment by ndushay** [comment]
Started a plugin gem for this at https://github.com/sul-dlss/spotlight-resources-iiif

Didn't get too far, but was able to spin up the test app, as I recall.  Also, from commit history:  

- "first passing test:  feature that IIIF Manifest upload form exists"
- Rakefile add task for running spotlight locally with this gem and Sol

I know I got the running rails test app to display the IIIF upload form and could edit the form.  The form doesn't do anything yet, tho.

I was basing this gem partly on spotlight-dor-resources, partly on https://github.com/jkeck/spotlight-flickr-resources, partly on https://github.com/cbeer/spotlight-atom etc.

**Comment by ndushay** [comment]
I have also have some example manifests I was thinking of loading as fixture objects:  a single image canvas, a 2 image canvas, and a many-image canvas.

**Comment by aeschylus** [comment]
This is a good test [collection](http://iiif.io/api/presentation/2.0/example/fixtures/collection.json) (from Rob; organised intentionally like base-case fixture data), and this is [a list](https://github.com/UniversalViewer/manifesto/tree/master/test/fixtures) of some deliberately weird manifests that have more realistic content.

**Comment by ndushay** [comment]
Thanks, Drew -- the fixture objects I emailed are the straightforward cases, I think.

**Comment by aeschylus** [comment]
@jkeck, @peetucket Not sure if this is the issue corresponding to this set of work, but here is a diagram from the specs that puts everything into its place:

[!](http://iiif.io/api/presentation/2.0/img/objects-all.png)

**Comment by cbeer** [comment]
https://github.com/UniversalViewer/manifesto/tree/master/test/fixtures

**Comment by cbeer** [comment]
We should test this with exhibits-stage.stanford.edu and see if we like it.

**Comment by snydman** [comment]
We don't like it.  I tried to add an item from Digital Bodleian (http://iiif.bodleian.ox.ac.uk/iiif/manifest/fc19f743-01b2-472c-8692-fd6326c7f84c.json) and the image does not display, and title information is incorrect.  I tried a second item from a different IIIF repository - Yale Center for British Art (http://manifests.britishart.yale.edu/manifest/67557) with the same result.

**Comment by jkeck** [comment]
@snydman would you say that you've indicated the issues described here in sul-dlss/exhibits#190?

**Comment by jkeck** [comment]
Ticket about brining this into spotlight-core: #1714

Other issues will be fixed as part of looking into sul-dlss/exhibits#190

**Comment by nicolasfranck** [comment]
When I try to add items from an IIIF collection, it also creates an "empty" item that corresponds to the collection itself:

* no thumbnail
* no metadata
* solr document:
  * iiif_manifest_url_ssi is equal to the collection uri
  * collection_id_ssim does not exist

e.g. http://adore.ugent.be/IIIF/collections/BenedictinesGhentStPeter

When I add a thumbnail service to the collection the "empty" item gets a thumbnail.

What is the use case for adding these collections also to the index? Or should I just make these collections "private"?
