### ISSUE TITLE
Add new user role with more limited permissions

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1155]
Details TBD. Goal is to support the use case of a class collaboratively building an exhibit. In that scenario it might not be a good idea for all students to have permission for all the actions curators can currently do (e.g., configure metadata, facets, etc.).

**Comment by cbeer** [comment]
We can easily accomplish this in spotlight, or in local applications, once we define what the permissions are.

**Comment by ggeisler** [comment]
Closing this in favor of #2585, although it's not the exact same use case (but the original use case in this ticket has gone away and I haven't heard it come up again. I think it'll be better for someone to write a new ticket if a similar case comes up.)
