### ISSUE TITLE
HTML comment rendered as visible text

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1162]
A curator cut and pasted text to the Text widget (see homepage of Muybridge). In edit mode, everything looks fine:

![curation_-_edit_page___eadweard_muybridge_collection_-_stanford_university_libraries](https://cloud.githubusercontent.com/assets/101482/9504168/f286a0aa-4bef-11e5-90dd-bb3e56b0ab6f.png)

But when the page is saved, it looks like this, with HTML comments rendered:

![eadweard_muybridge_collection_-_stanford_university_libraries](https://cloud.githubusercontent.com/assets/101482/9504207/272e4092-4bf0-11e5-89dc-4e251fc8ba0f.png)

I'm not sure why the copied text includes the HTML comments `<!--StartFragment-->` and `<!--EndFragment-->` but I wonder if we can do anything to prevent the HTML comments from showing up in the rendered page, so that HTML comments are hidden as they are in edit mode. 

(The reason for the difference seems to be because the HTML comment is inside quotations in the paragraph tag of the rendered page, but outside of quotations in the edit page. I just don't know why this is different between the edit and view modes, and if this might be easily addressed.)

**Comment by cbeer** [comment]
I'm having trouble recreating this.. Were you able to do it?

**Comment by ggeisler** [comment]
No, because I don't know exactly how the curator ended up with the HTML comment added to his copied text. I assume it is some sort of browser extension but that's just a guess. The curator does not seem to know why it is happening.

I gave him a workaround (paste to a text editor and clean up before pasting back into Spotlight) so this isn't an immediate problem. It might be extremely unlikely to happen again (it happened to this curator every time he copied and pasted, but this might be unique to his technology setup) so if it isn't straightforward to just strip out HTML comments in ST text boxes before saving the page we could just icebox this and see if it comes up again in the future.

**Comment by cbeer** [comment]
:+1:. Everything I tried just gave me visible HTML comments in both the editor and the page, which seems like a pretty good outcome.
