### ISSUE TITLE
Add IIIF support for uploaded images using rack-iiif

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/spotlight#1182]
Spotlight accepts image uploads using Carrierwave. By default, I believe these end up somewhere in `./public`. We should put a IIIF shim in front of these uploads, perhaps using the `rack-iiif` or `riiif` gems.

https://github.com/IIIF/rack-iiif
https://github.com/curationexperts/riiif

**Comment by jcoyne** [comment]
I don't think that rack-iiif is production ready yet.
