### ISSUE TITLE
Spotlight sidecar doesn't work on a multivalued unique_key

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#1364]
Yes, I know that Multivalued unique key sounds suboptimal.

Here's the workaround we used:

``` ruby
# app/models/solr_document.rb
...
  def [](key)
    if key.to_s == self.class.unique_key
      return Array(super).first
    end
    super
  end
...
```

**Comment by cbeer** [comment]
I wasn't aware you could even do that. Apparently this came up for Blacklight too, and people were surprised or thought it was wrong: https://github.com/projectblacklight/blacklight/issues/623
