### ISSUE TITLE
Undefined table "versions" when installing from template

### ISSUE THREAD

**Issue by ronan-mch** [projectblacklight/spotlight#1429]
After installing from the template as described in `Readme.md` and creating an exhibition, I encounter the following error:

> ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "versions" does not exist
> LINE 5:                WHERE a.attrelid = '"versions"'::regclass
>                                           ^
> :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
>                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
>                 FROM pg_attribute a LEFT JOIN pg_attrdef d
>                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
>                WHERE a.attrelid = '"versions"'::regclass
>                  AND a.attnum > 0 AND NOT a.attisdropped
>                ORDER BY a.attnum

The problem seems to be that the generator and migrations for the paper_trail gem are not being installed in the template.

adding the following to `template.rb` would probably fix this error:

``` ruby
generate "paper_trail:install"
rake 'db:migrate'
```

**Comment by cbeer** [comment]
I believe we've since documented running `db:migrate`, and fixed the template to make sure it is run if it is necessary.
