### ISSUE TITLE
Undefined table 'friendly_id_slugs' when installing from template

### ISSUE THREAD

**Issue by ronan-mch** [projectblacklight/spotlight#1430]
Similar problem to #1429 

Adding 

``` ruby
generate "friendly_id" 
rake "db:migrate" 
```

to `template.rb` should fix it. I can put a PR with both of these fixes if you agree with my solution?

**Comment by cbeer** [comment]
I believe we've since documented running `db:migrate`, and fixed the template to make sure it is run if it is necessary.
