### ISSUE TITLE
Postgres type mismatch error with taggable

### ISSUE THREAD

**Issue by ronan-mch** [projectblacklight/spotlight#1433]
> PG::UndefinedFunction: ERROR: operator does not exist: character varying = integer LINE 1: ...= 'Spotlight::Exhibit') AND (taggings.taggable_id IN(SELECT ... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

``` SQL
SELECT COUNT(*) FROM "tags" JOIN (SELECT taggings.tag_id FROM "taggings" WHERE (taggings.taggable_type = 'Spotlight::Exhibit') AND (taggings.taggable_id IN(SELECT spotlight_exhibits.id FROM "spotlight_exhibits" WHERE ('t'='t') AND "spotlight_exhibits"."published" = 't' ORDER BY weight ASC)) GROUP BY taggings.tag_id) AS taggings ON taggings.tag_id = tags.id
```

To reproduce: Use postgres, create multiple exhibitions with a tag, return to home screen. Or from the rails console: `Spotlight::Exhibit.all.all_tags`

**Comment by ronan-mch** [comment]
Seems to arise from this line:
https://github.com/sul-dlss/spotlight/blob/master/app/views/spotlight/exhibits/index.html.erb#L19

which refers to the `all_tags` method from `acts-as-taggable`: https://github.com/mbleigh/acts-as-taggable-on/blob/fac92a9114d20bf71595c1e4b1e8ec622fc2f190/lib/acts_as_taggable_on/taggable/collection.rb#L55

**Comment by dunn** [comment]
This is still present when running 2.2.0 and PSQL 9.2.

**Comment by dunn** [comment]
So it is; @jcoyne noticed the same thing a while back https://github.com/mbleigh/acts-as-taggable-on/issues/853
