### ISSUE TITLE
Display bug on Safari (likely flexbox-related?)

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1444]
There are a couple of contexts where content flows horizontally beyond the expected boundary in Safari OS X. These are gallery view of results and the item row widget. Both of these use flexbox so that seems a potential culprit, although http://caniuse.com/#feat=flexbox seems to indicate Safari 9 fully supports flexbox. Examples:

### Item Row widget
![haydn___memorial_library_of_music_test_site_-_online_exhibits](https://cloud.githubusercontent.com/assets/101482/13329095/fbc5537c-dba6-11e5-8f4d-4b06f0f7329a.png)

--
### Gallery view of search results
![language__english_-_maps_of_africa__an_online_exhibit_-_online_exhibits_search_results](https://cloud.githubusercontent.com/assets/101482/13329138/26b4a876-dba7-11e5-8e56-4bb5a2778322.png)

**Comment by cbeer** [comment]
Possibly related to https://github.com/projectblacklight/blacklight-gallery/commit/ba61fd59731b915a19506f0c0ff68f89ce689f54?

**Comment by jcoyne** [comment]
This works fine for me on Safari 9.1.1: https://exhibits.stanford.edu/maps-of-africa/catalog?f%5Blanguage%5D%5B%5D=English&q=&search_field=search&view=gallery

Perhaps it's been fixed in Safari since this was reported?

**Comment by ggeisler** [comment]
It does look like the gallery view problem is fixed (via [projectblacklight/blacklight-gallery@ba61fd5](projectblacklight/blacklight-gallery@ba61fd5) @cbeer pointed out above?). But I still see the problem with the Item Row widget.

Images wrap as expected in Chrome and FF:

![chrome](https://cloud.githubusercontent.com/assets/101482/16693811/d5e35c86-44eb-11e6-83c2-f04d2a5423fd.png)

But not in Safari 9.1.1:

![safari](https://cloud.githubusercontent.com/assets/101482/16693826/e6e3a45a-44eb-11e6-888c-c798c275eabb.png)

For an example on a published exhibit, compare this page in Safari versus Chrome:
https://exhibits.stanford.edu/rare-music/feature/early-american-tune-books

**Comment by cbeer** [comment]
The gallery doesn't surprise me -- we updated blacklight-gallery, which has that safari flexbox fix applied.
