### ISSUE TITLE
Browse categories widget - include item counts bug

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1456]
The `Include item counts?` checkbox on the Browse Categories widget always returns to the true state when the page is saved. If you uncheck it and save your changes, the item counts still show in the rendered widget and when you re-edit the page the checkbox is back to being checked.

![curation_-_edit_page___test_-_blacklight](https://cloud.githubusercontent.com/assets/101482/16167389/1e1c4790-34a9-11e6-827e-b3e149a7db2b.png)

**Comment by cbeer** [comment]
Fixed by #1489
