### ISSUE TITLE
Browse category results always default to gallery view

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1458]
Even when the Configuration > Search > Results is configured so that gallery view is not enabled, going to the results page for a browse category displays results in the gallery view (in the screenshot below, only list view and slideshow view are enabled):

![digital_maps___test_-_blacklight](https://cloud.githubusercontent.com/assets/101482/16248383/ab78ceca-37c3-11e6-9070-61611c6dc666.png)

This is even the case when only one view is enabled; in the screenshot below only list view is enabled, but the browse category results show in gallery view.

![digital_maps___test_-_blacklight 2](https://cloud.githubusercontent.com/assets/101482/16248454/24aed244-37c4-11e6-9881-a18b72b069e8.png)

In both cases, the regular search results views behave as expected - the problem is only with browse category results.

**Comment by cbeer** [comment]
We're getting the gallery view because it is set as a global default:
https://github.com/projectblacklight/spotlight/blob/master/lib/spotlight/engine.rb#L155

@ggeisler What should the behavior be when the gallery is disabled (right now, we'd fall back on the list view, or whatever the default view is)? I wonder if we ought to give the user an explicit way to select the view?

**Comment by ggeisler** [comment]
Giving the user an explicit way to select the view would be great if feasible. Could we do it similar to the normal search result selection, where the curator can select more than one? With Gallery as a default (and fallback if they uncheck all boxes)?

So similar selection to normal search result types, but completely independent.

![curation_-_edit_page___test_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/16741956/82360946-475a-11e6-8675-4fbbdbc1d53f.png)

**Comment by cbeer** [comment]
Oh, are we talking about letting the curator decide what views are available for a given browse category? I assumed we'd just let the curator pick the default view, and the available views would come from the search configuration.

If we're letting the curator choose all the available results, then how do they choose the default?


Maybe something like:

![screen shot 2016-07-11 at 2 39 41 pm](https://cloud.githubusercontent.com/assets/111218/16747831/98ccfb68-4775-11e6-95b2-c6b7ea0267ea.png)

**Comment by ggeisler** [comment]
Good point. I like your approach (though I wouldn't show the icons in the radio buttons, if that was intentional).

**Comment by cbeer** [comment]
Fixed by #1488
