### ISSUE TITLE
List widget display bug

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1464]
There's an issue with the Sir Trevor List widget where each time the page in which it is embedded is saved, the list is indented, because the initial `ul > li` structure is wrapped in an additional `ul` on every page save.

First time the list is saved:
![page_one___test_2_-_blacklight](https://cloud.githubusercontent.com/assets/101482/16535078/6b81b222-3f99-11e6-89d4-cb2e37cb1c3a.png)

Third time the list is saved:
![page_one___test_2_-_blacklight 3](https://cloud.githubusercontent.com/assets/101482/16535085/7348ea02-3f99-11e6-9a3b-7a22b6f00616.png)

See the extra two `ul` tags that the initial list is wrapped in after the third save:

![page_one___test_2_-_blacklight 4](https://cloud.githubusercontent.com/assets/101482/16535111/a4ba12fa-3f99-11e6-9077-1eb38eb51412.png)

**Comment by cbeer** [comment]
Blocked by #1485.
