### ISSUE TITLE
Support Rails 5

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/spotlight#1468]
Tracking upstream issues:
- [x] https://github.com/projectblacklight/blacklight/pull/1425
- [x] https://github.com/mbleigh/acts-as-taggable-on/issues/762
- [x] https://github.com/plataformatec/mail_form/pull/46 (removed dependency)
- [x] https://github.com/madebymany/sir-trevor-rails/pull/52
- [ ] breadcrumbs_on_rails (https://github.com/weppos/breadcrumbs_on_rails/issues/82)

**Comment by jcoyne** [comment]
It looks like a [fix](https://github.com/mbleigh/acts-as-taggable-on/pulls/720) for the second bullet has been merged into master. So we just await a new release of `acts-as-taggable-on`

**Comment by jcoyne** [comment]
@cbeer how do you feel about pointing at the master branch of AATO?

**Comment by cbeer** [comment]
:shrug: .. I'm hoping they'll get a release out soon enough.

**Comment by cbeer** [comment]
We're also waiting for mail_form, apparently, used only by `ContactForm`. Maybe we can just sever that dependency and just use actionmailer (since it seems to be pretty lightly maintained..)?

**Comment by cbeer** [comment]
and breadcrumbs_on_rails; maybe replace it with https://github.com/lassebunk/gretel?

**Comment by jcoyne** [comment]
There is a 4.0.0.pre release version of AATO
