### ISSUE TITLE
Spotlight template generator is incompatible with Rails 5

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#1473]
When running the template generator with `0.17.0 - 0.18.0` the generator will automatically add `gem 'rails', '~> 5.0.0'` to the generated applications `Gemfile` causing dependency conflicts.

**Comment by cbeer** [comment]
Hopefully we'll fix this with #1468. Until then, I'm not sure what we can do. By the time Rails gets to this generator, it's too late for us to specify a version of Rails.

**Comment by cbeer** [comment]
Mostly fixed by #1483.
