### ISSUE TITLE
Upgrade to sir-trevor 0.6

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/spotlight#1485]

**Comment by jcoyne** [comment]
Are there compelling reasons to upgrade?

**Comment by cbeer** [comment]
It'll fix #1464, plus make some of our overrides much less clunky.

**Comment by raffij** [comment]
If you find things you need in 0.6 and beyond then add an issue. There have been lots of changes since the version you are using so might be a reasonably large upgrade looking at the number of blocks you have.
