### ISSUE TITLE
Opengraph helper should return meta tags containing the opengraph metadata from the Spotlight resource

### ISSUE THREAD

**Issue by mjgiarlo** [projectblacklight/spotlight#1503]
The [opengraph helper](https://github.com/projectblacklight/spotlight/blob/master/app/views/layouts/spotlight/spotlight.html.erb#L24) should return meta tags containing the opengraph metadata from the Spotlight resource (to enable, e.g., Facebook rich snippets). Originally surfaced as part of sul-dlss/exhibits#218.

The helper currently returns an empty string. FWIW, I don't consider this bug high priority, because Facebook is somewhat smart about inferring snippet properties from the page. *I.e.*, snippets ​already​ work in Facebook without fixing this helper. (The advantage of fixing this is we'd have more predictability and control over how snippets appear.) Note too that other consumers of opengraph metadata may not do as good a job at inferring properties.

**Comment by mjgiarlo** [comment]
Note: #1506 may be removing indexing of open graph properties. See that PR for more info.

**Comment by jcoyne** [comment]
@mjgiarlo the OpenGraph stuff is for harvesting open graph resources into your exhibit. It's not for producting OpenGraph fields on your exhibit documents
