### ISSUE TITLE
Spotlight::Resources::Upload should be resolvable over RIIIF

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#1545]
Either a second riiif endpoint or, make them be a subclass of FeaturedImage.
- [ ] https://github.com/projectblacklight/spotlight/pull/1498/files#diff-f3f129357f79bfbaa265835b5ecedf64R5
- [ ] https://github.com/projectblacklight/spotlight/pull/1498/files#diff-08eb7a91375579a73c29acba50d7bbe0R38

**Comment by jkeck** [comment]
I believe this is done already, `Spotlight::Upload` uses the `Spotlight::FeaturedImage` class for its uploader.
