### ISSUE TITLE
When replacing an image (for the crop tool), the OSD window does not reinitialize

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#1569]
After replacing an image it looked like this:
<img width="895" alt="screen shot 2016-08-05 at 12 47 50 pm" src="https://cloud.githubusercontent.com/assets/92044/17446237/ea45dd92-5b0d-11e6-90b4-4448f1847952.png">

But it should have looked like this:

<img width="901" alt="screen shot 2016-08-05 at 12 49 06 pm" src="https://cloud.githubusercontent.com/assets/92044/17446243/eff950d4-5b0d-11e6-9fd3-abd07499b55f.png">

**Comment by jkeck** [comment]
@jcoyne feels that we're storing all the information necessary to reinitialize the OSD window with the correct region selected.  This may be a javascript bug that we need to track down.

**Comment by tingulfsen** [comment]
After rebasing the iiif_crop branch that @jcoyne wrote on the current master branch, I have been unable to reproduce this issue.
