### ISSUE TITLE
Styling problem when editing widgets

### ISSUE THREAD

**Issue by hepplerj** [projectblacklight/spotlight#1572]
Yesterday I noticed a problem with the styling in the widget editing panes (in Safari), please see the attached screenshots. I haven't been able to replicate the issue, but I did see the issue again on someone else's machine when I was walking through how to edit pages in Spotlight. I believe he was running Chrome.

<img width="353" alt="screenshot 2016-08-09 10 53 41" src="https://cloud.githubusercontent.com/assets/153271/17560564/69e60622-5ed7-11e6-8a2a-e0b4bc17365c.png">

<img width="322" alt="screenshot 2016-08-09 10 53 34" src="https://cloud.githubusercontent.com/assets/153271/17560565/69fd4bfc-5ed7-11e6-8ca8-cf0d251ed4b8.png">

**Comment by jkeck** [comment]
I'm closing this issue has SirTrevor (our widget framework) has updated their UI and the Close button is now rendered as a small grey `X` in the upper right-hand corner.
