### ISSUE TITLE
Style problem when adding/editing tags at the item level

### ISSUE THREAD

**Issue by hepplerj** [projectblacklight/spotlight#1573]
We noticed that when you're looking at an item and select Edit, the styling around the tag input isn't quite right (notice the cursor). 

<img width="445" alt="screenshot 2016-08-09 12 36 55" src="https://cloud.githubusercontent.com/assets/153271/17573987/decb5f06-5f12-11e6-9b50-900c4a14abde.png">

**Comment by caaster** [comment]
@cbeer Has this fix been deployed to prod? Is it possible to comment on tickets to that effect? This would be super helpful for tracking completion of issues reported by users. Thanks!
