### ISSUE TITLE
PDF previews and enhancements

### ISSUE THREAD

**Issue by hepplerj** [projectblacklight/spotlight#1574]
More general questions about the potential roadmap regarding PDF files: 

a. Are there plans in place to handle creating a thumbnail in list/gallery/masonry views for PDF files rather than a blank box (or, alternatively, a default image or icon; or a way to attach your own thumbnail)? 

b. At the Item level for an object that's a PDF, are there plans for allowing the PDF to be viewed within the browser rather than download only?

**Comment by caaster** [comment]
This is not a Spotlight issue. sul-embed issue
