### ISSUE TITLE
Autocomplete not working for Browse and Feature Page widgets

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1606]
When using the Browse Categories widget and the Feature Page widget, typing the name of a browse category or feature page does not change the items shown in the selection overlay. Autocomplete does work in widgets where you are typing the name of an item, rather than a browse category or feature page title.

In this example below, "Portraits" is a valid browse category title.

![curation_-_edit_page___new_exhibit_for_yale_-_online_exhibits](https://cloud.githubusercontent.com/assets/101482/18290599/fcda0aac-7438-11e6-866c-94e826899ee4.png)

This is a blocker for at least one current exhibit, where the curator is not able to select desired feature page titles from a long list (the desired title isn't visible in the default selection overlay due to #1603).

**Comment by jkeck** [comment]
Non-solr backed autocompletes (e.g. active record objects like pages and browse categories) simply return json for **all** the objects and let's the autocomplete library filter them.

Solr backed autocompletes returns the json for matching documents and no client side filtering is necessary.

If this worked before something must have changed in the the twitter typeahead library.

`prefetch` is the correct thing to use for this use-case, so I'm going to work on being able to somehow pass the kind of typeahead a block will use (remote or prefetch).

**Comment by ggeisler** [comment]
I'm not sure that autocomplete ever worked for the browse/feature page widgets; I probably should've stated the original ticket description more like: autocomplete is something that we need for the browse/feature page widgets that currently doesn't exist. It hadn't surfaced as a need until now, because we hadn't had an exhibit with enough browse categories/feature pages to make autocomplete necessary feature for finding a desired category/page.

**Comment by jkeck** [comment]
Thanks for the clarification @ggeisler!
