### ISSUE TITLE
Slideshow widget not displaying all images (some are broken)

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1607]
See 2 exhibit examples:
https://exhibits.stanford.edu/rare-music
https://exhibits.stanford.edu/mss

**Comment by jcoyne** [comment]
Stacks is giving us a 404 for some of the URLs.  Example: https://stacks.stanford.edu/image/iiif/gj142zc9471/gj142zc9471_00_0009/full/full/0/default.jpg

**Comment by caaster** [comment]
P.S. I did check some of the images in question to verify that I could view images via PURL pages -- verified.

**Comment by jcoyne** [comment]
So now the question is are we indexing a bad URL, or is Stacks not providing an image when it should.

**Comment by jcoyne** [comment]
I think the problem is with Stacks. Firefox is saying:
> The image "https://stacks.stanford.edu/image/iiif/gj142zc9471%2Fgj142zc9471_00_0009/full/full/0/default.jpg" cannot be displayed because it contains errors"

**Comment by jcoyne** [comment]
It appears that all images are showing now.  This was due to a problem with the Stacks IIIF server @ Stanford and not with spotlight
