### ISSUE TITLE
Search Configuration Sort Fields drag and drop/reordering works -- but isn't saving

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1608]
Reported by curator. @ggeisler verified: I experience the same problem as Daniel reported. I tried moving title from the last to the first field but after saving it is still listed last. The reorder *appears* to work, but saving the new order is not successful. I tried using Chrome, Safari, and FF, just to be sure it wasn’t a browser bug.

**Comment by jkeck** [comment]
I believe this is caused by a space in the id attribute of the sort field.
