### ISSUE TITLE
Metadata "Deselect All" for Gallery View doesn't save as a preference

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1625]
This configuration is strangely buggy.

My experience:
1. I configured search result type pages to show list view & gallery view and then hit save
2. I configured metadata to not display any metadata for gallery view by choosing "deselect all" and then hit save
3. I configured all my browse categories to display gallery view as the default view (and saved 'em all)
4. Then I navigated to the browse tab for my exhibit to verify the above selections
5. Gallery view displays as the default view, but also displays numerous metadata fields
6. Then, I click on list view for each browse category, and then click back on gallery view
7. Then, and only then, does gallery view display with a title only, and no other metadata

**Comment by ggeisler** [comment]
Maybe a caching issue? I think I've noticed that I sometimes have to refresh a page after making a change to actually see the change.

**Comment by caaster** [comment]
I've factored that in, in my trouble shooting.

Sent from my iPhone

On Oct 26, 2016, at 5:18 PM, Gary Geisler <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe a caching issue? I think I've noticed that I sometimes have to refresh a page after making a change to actually see the change.

-

**Comment by caaster** [comment]
I've looked at this again, and I am no longer seeing the same problem. Therefore closing this ticket.
