### ISSUE TITLE
The carousel on slideshow presentation of search results reloads the page when advanced

### ISSUE THREAD

**Issue by jeremythuff** [projectblacklight/spotlight#1629]
When pulling up search results in the slide show view, the carousel's next and previous navigation arrows are anchor tags and are triggering a page refresh when clicked, which closes the carousel. 

I have fixed this in our instance by adding bit of javascript:

```
Spotlight.onLoad(function() {
   $(".carousel-control").on("click", function(e) {
    e.preventDefault();
  });
});
```

If this is an acceptable solution I will be happy to make a PR.

**Comment by jcoyne** [comment]
Yes, I'm seeing that error too.  That should probably be fixed in here: https://github.com/projectblacklight/blacklight-gallery/blob/master/app/assets/javascripts/blacklight_gallery/slideshow.js#L83-L88

**Comment by jeremythuff** [comment]
PR https://github.com/projectblacklight/blacklight-gallery/pull/38

**Comment by mejackreed** [comment]
This has been resolved upstream, please update to blacklight-gallery v0.9.0 or greater.
