### ISSUE TITLE
Openseadragon does not reload on naivigation

### ISSUE THREAD

**Issue by jeremythuff** [projectblacklight/spotlight#1630]
Openseadragon's initialization phase only runs on a complete page refresh. This results in embedded images not being loaded in the viewer when in app navigation is used (i.e. clicking one the "Home" link.) 

To recreate upload an image and use the embedded image widget to place it in the home of the exhibit. The image will appear when reloading the page, but not when the home button in clicked.

We have fixed this by adding `$(".openseadragon-container").find("picture:not([id])").openseadragon();` to an `Spotlight.onLoad()` callback. I would be happy to make a PR if this a good way to deal with this.

**Comment by cbeer** [comment]
I think we'll want to fix this upstream in openseadragon-rails. It looks like it isn't set up to support Turbolinks 5: https://github.com/cbeer/openseadragon-rails/blob/master/app/assets/javascripts/openseadragon/rails.js#L8.

**Comment by jcoyne** [comment]
Fixed in https://github.com/cbeer/openseadragon-rails/pull/19

**Comment by jeremythuff** [comment]
I am now experiencing the images being placed on the page twice.

**Comment by wwelling** [comment]
The fix upstream may open the image during navigation without page reload, but the openseadragon-viewer now adds duplicate openseadragon-container.

**Comment by wwelling** [comment]
I believe this can be closed.
