### ISSUE TITLE
Heading widget outputs <p> inside an <h2>

### ISSUE THREAD

**Issue by starsplatter** [projectblacklight/spotlight#1633]
When I insert a heading on a Mac in Firefox or Chrome the markup it generates is
`<h2><p>My heading</p></h2>
`
This doesn't seem like what you would want.

Locally I fixed this by not putting it through the markdown filter but I'm not sure if that is an unsafe solution.

**Comment by jkeck** [comment]
@tingulfsen can you see if this is no longer a problem  when you diff our header widget with the sir-trevor widgets in the context of the list widget bug?
