### ISSUE TITLE
Generate IIIF Manifests for Documents

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/spotlight#1641]
Generate IIIF manifests to make content accessible to external IIIF users.

Note that this does not do anything to address our image performance problem.

**Comment by cbeer** [comment]
Related to #1226?

**Comment by jkeck** [comment]
See projecthydra-labs/hyku#118

**Comment by cncoleman** [comment]
Does this mean that for any spotlight exhibit, we can include a link to open the exhibit images in a IIIF viewer like Mirador or UV?

**Comment by jkeck** [comment]
For the scope of this ticket we would simply by generating IIIF manifests for the documents themselves.

So the documents would be able to be opened in a IIIF compatible viewer, but there would not be a manifest for the exhibit itself that would allow all the images in an exhibit to be opened in a IIIF compatible viewer via a single manifest (not sure if that's what you were asking).

**Comment by cncoleman** [comment]
@jkeck Yes, that's what I was asking. Thank you for clarifying. The idea is to re-use the work (time and effort) done to curate spotlight exhibits at Stanford by making those images available as collections that can be opened in Mirador.stanford.edu. The assumption is that the exhibit has value because of the curation effort that went into it.

**Comment by jkeck** [comment]
Ah, absolutely.  That has been something that has been discussed since the beginning of Spotlight (ensuring that the value of the organization could be persisted/re-used in some way).

This is certainly something we should consider (albeit out of scope for this ticket). 

Would you be willing to submit a new issue to this repository about generating a IIIF manifest for the exhibit?

Thanks!
