### ISSUE TITLE
OSD image crop stopped working?

### ISSUE THREAD

**Issue by tingulfsen** [projectblacklight/spotlight#1646]
With the latest version of Google Chrome I am unable to use the cropping tool - there is nothing in the JavaScript console and no movement at all in the tool. This is for the iiif_crop branch after rebasing on master.

**Comment by jkeck** [comment]
This was on the appearances page when uploading an image from the local file system.

**Comment by jcoyne** [comment]
@tingulfsen have you tried the demo app from https://github.com/sul-dlss/iiif-cropper with that browser?  I wonder if this ticket should be filed in that repo.

**Comment by jkeck** [comment]
Ticket filed: sul-dlss/iiif-cropper#44
