### ISSUE TITLE
Add default thumbnail for browse category

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/spotlight#1685]
With the move to IIIF, it's a bit unsatisfying to have to write IIIF manifest parsing code just to fetch the first image of the first document in the exhibit (which may not exist).

If we could instead have a placeholder image, that could indidcate to the user that they should choose a good image for the browse category, exhibit etc.

**Comment by ggeisler** [comment]
@jkeck Here's the placeholder image we discussed:

![placeholder_thumbnail](https://cloud.githubusercontent.com/assets/101482/22570991/9eb8679a-e952-11e6-9397-b0a36dad4daa.jpg)
