### ISSUE TITLE
Masthead + thumbnail cropping loses (or, rather, doesn't expose) multi-image context

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/spotlight#1693]
After cropping a thumbnail or masthead from a multi-image work, when I revisit the masthead/thumbnail page, I should see some indication of which image was cropped.

**Comment by jkeck** [comment]
I have a branch working for this, but it really should build off of the improvements in #1692 (and will most likely change considerably because of it).  I'll keep my branch for reference, but don't want to get into refactoring things too much until I can work from #1692.

**Comment by jkeck** [comment]
Closed by #1719
