### ISSUE TITLE
Thumbnail cropping for Home Page

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/spotlight#1698]
There is an option to crop thumbnails for the home page of an exhibit.  This currently does not work in the latest release of exhibits (and we believe that it is not intended to).

Thumbnails are intended to be cropped for Feature Pages (as there is a SirTrevor widget that allows you to add the thumb + link to a Feature Page on another page).

With the IIIF cropping work, we set this up to work (since it was in the UI), but that may have been an oversight.

Should we remove the option to crop a thumbnail for the home page?

**Comment by cbeer** [comment]
We decided to just support thumbnail cropping for all page types.
