### ISSUE TITLE
Updating spotlight (and other gems)

### ISSUE THREAD

**Issue by travisLilleberg** [projectblacklight/spotlight#1721]
Hello, this is more a question than an issue.

I'm trying to get our spotlight instance up to the current version. We're back on 0.30. When I try to boot up after updating my gems, I get the error:
> couldn't find file 'jquery.jcrop' with type 'text/css'

I understand why this is happening. The template that we used to install our instance created a `require jquery.jcrop` line in spotlight.scss. The newest version doesn't use jcrop anymore, and new instances won't have that line. Versions of gems in the Gemfile also have changed across the templates.

Is there any way that I can update files like this to match the new template, instead of the template we used initially? Or do I just need to hunt down all the incongruities? I read through the Rails Application Template docs, but I didn't see anything on this.

Thank you,

-- Travis Lilleberg

![spotlight-scss-diff](https://cloud.githubusercontent.com/assets/8809048/22708328/d2d8985c-ed43-11e6-8866-a207449b2e97.png)

**Comment by jkeck** [comment]
@travisLilleberg I believe you're installing from master?

When we cut a release with our current work, we will provide upgrade instructions (which definitely includes the change required to address this).

To fix this now, you can look at what the generated file should look like at https://github.com/projectblacklight/spotlight/blob/master/lib/generators/spotlight/templates/spotlight.scss

You're going to run into some other issues most likely though, so you may want to wait until we have a stable release before upgrading.

**Comment by travisLilleberg** [comment]
Alright, I'll wait. Thanks.
