### ISSUE TITLE
Don't know how to build task 'spotlight:server'

### ISSUE THREAD

**Issue by tdodson** [projectblacklight/spotlight#1739]
I followed the install directions, with everything progressing just fine, but whenever I try to run "rake spotlight:server" from the Terminal I get the following error: 
Don't know how to build task 'spotlight:server' (see --tasks)
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'

**Comment by cbeer** [comment]
Hi @tdodson  -- it looks like you found a mistake in the README. We've updated it accordingly.
