### ISSUE TITLE
App 30245 stderr: user_for_paper_trail is present, but whodunnit has not been set.

### ISSUE THREAD

**Issue by wwelling** [projectblacklight/spotlight#1748]
This error occurs in Apache error log when hosting rails using Phusion Passenger. I assume it will be the same for other web servers. I have seen it for the sessions_controller, registration_controller, images_controller, and catalog_controller so far. Does not seem to appear if just browsing the exhibit anonymously.

Here is the log for the images_controller:

```
App 30245 stderr: /home/spotlight/.rvm/gems/ruby-2.3.0/gems/riiif-1.1.0/app/controllers/riiif/images_controller.rb:
App 30245 stderr: user_for_paper_trail is present, but whodunnit has not been set.
App 30245 stderr: PaperTrail no longer adds the set_paper_trail_whodunnit callback for
App 30245 stderr: you. To continue recording whodunnit, please add this before_action
App 30245 stderr: callback to your ApplicationController . For more information,
App 30245 stderr: please see https://git.io/vrTsk
```

**Comment by travisLilleberg** [comment]
I got rid of the error by adding the following to the bottom of ApplicationController:

```
def user_for_paper_trail
   nil
end
```
