### ISSUE TITLE
Customizing the Heading Sir Trevor block

### ISSUE THREAD

**Issue by travisLilleberg** [projectblacklight/spotlight#1758]
Hello,

I'm looking to add a couple radio buttons to the Sir Trevor heading block, allowing people to choose between "Heading" (h2) and "Subheading" (h3).

I'm having trouble modifying the editor html. It appears to be hard coded into the Sir Trevor library.

```
module.exports = Block.extend({
  type: 'heading',
  editorHTML: '<h2 class="st-required st-text-block st-text-block--heading" contenteditable="true"></h2>',
```

Am I missing something? Should I create my own heading block? 

Thanks,

-- Travis Lilleberg

**Comment by jkeck** [comment]
Yeah, I believe you're right that the html element is hardcoded in the SirTrevor block code.  That is typically the pattern for SirTrevor blocks.  In other cases where we've needed to override default SirTrevor block behavior we have overridden that block either in the Spotlight codebase or in a local application where the behavior didn't make sense generically in Spotlight.

**Comment by travisLilleberg** [comment]
Alright, sounds good. Thanks.
