### ISSUE TITLE
Feature Page widget not displaying correctly

### ISSUE THREAD

**Issue by travisLilleberg** [projectblacklight/spotlight#1761]
Hello,

We seem to be having issues with the "Feature Pages" widget on our site. I've attached screen shots of the edit page and the actual display.

Specifically, if we include 4-5 features pages in the row, it only shows 3 pages: 

![4 edit screen](https://cloud.githubusercontent.com/assets/8809048/23516956/d1dd0a72-ff3c-11e6-98bc-77e0aee63b4a.png)
![4 display](https://cloud.githubusercontent.com/assets/8809048/23516959/d6fcdfa0-ff3c-11e6-9f2d-b302e100a78b.png)

If you go 6+, the styles get really messed up and you just see the titles of the pages, overlapping the block above them:

![6 edit screen](https://cloud.githubusercontent.com/assets/8809048/23516964/d92d0fa2-ff3c-11e6-8d55-b52c80e3a5be.png)
![6 display](https://cloud.githubusercontent.com/assets/8809048/23516965/dab424be-ff3c-11e6-8a2e-2786167ea51c.png)

The only error I'm getting in console is:
`Failed to load resource: the server responded with a status of 404 (Not Found)` on thumb_default.png

Versions:
Spotlight - 0.30.0
Blacklight - 6.7.2
Blacklight Gallery - 0.6.1
Blacklight Oembed - 0.1.0
Rails - 4.2.6

Thanks for any help,

-- Travis Lilleberg

**Comment by jkeck** [comment]
Have you applied thumbnails to these pages?  I haven't looked too deeply into the code, but we may not set a default thumbnail for pages like we do for exhibits and browse categories.

You may want to look at the serialized block in the database do determine why 3 items are showing up when more are being saved.

Also, although I don't think this is related to anything we've done post v0.33.0, but you may want to upgrade your spotlight to v0.34.1 (keeping the migration path in mind).

**Comment by travisLilleberg** [comment]
I did set thumbnails on the pages, and I set a default thumbnail, but the result was the same.

Looking at _featured_browse_categories_block.scss, it appears that there's no support for feature rows bigger than 5, which would explain the oddness once you go past 6. categories-5 is largest category that has styles.  

As for the issue of the features only showing 3 items when 4 or 5 are selected, that appears to be in the css, lines 133-135. Category-4 and 5 are explicitly hidden when there's a sidebar on the page.

```
[data-sidebar="true"] {
  . . .  
  .category-4, .category-5 {                                                              
    display: none;                                                                        
  }
}
```

My users don't want a sidebar on their feature pages anyway. So that should be fine. I may add some help text to the block, just to warn them of these limitations.

Thanks again.

**Comment by cbeer** [comment]
> Looking at _featured_browse_categories_block.scss, it appears that there's no support for feature rows bigger than 5,

That seems like a bug. We should be able to define some base styles that make it work with any number of browse categories. I suspect we initially limited it to what displayed in a single row, maybe?

**Comment by ggeisler** [comment]
Yes, I believe the rationale behind the .scss was to present the number of featured browse categories that would look reasonable in a single row on the page (thus hiding items 4 and 5 if a sidebar is present and restricts the width of the main content area).

With this approach, if you want more than 3-5 featured browse categories in a visually contiguous block on the page, you would just use multiple instances of the widget consecutively, each with 3 or 5 category selections. For example, the bottom section of the homepage here uses two consecutive widget instances to feature 6 categories: https://exhibits.stanford.edu/feigenbaum

Not saying we couldn't figure out a better way to flow more than 5 selections in a single widget (e.g., flexbox) but I think the current .scss assumes you'll create multiple instances of the widget if you want to display more than 3-5 selections in one spot.

**Comment by travisLilleberg** [comment]
One option would be to make the feature page widget stop offering autocomplete boxes once you've hit 3 or 5 pages. I may try to implement that on our installation.

**Comment by caaster** [comment]
This issue has been reported by a curator here at Stanford as well.

**Comment by travisLilleberg** [comment]
For the time being, I've overwritten app/assets/javascripts/spotlight/blocks/pages_block.js in my application and added logic to to show/hide the input based on whether there should be any more feature pages in the row or not. It sets the limit to 3 pages if the sidebar is showing, 5 otherwise. If the block goes equal to or beyond the limit, it hides the input and displays a message saying why the input is gone.

I'll attach it here, in case it's useful to anyone else. I'd be happy to refactor it and make a pull request, if this functionality interests you guys.

**Warning:** I'm not up to date on my Spotlight version, so I can't guarantee it'll work for everyone.

https://gist.github.com/travisLilleberg/6a8061cf9635689edb77a702e75d3316

-- Travis

**Comment by starsplatter** [comment]
We ran into this issue today at Cornell as well. I think what I am going to do locally is update the curator UI to make the limitation clear, at least for now.
