### ISSUE TITLE
Page edit bug based on cursor position

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1769]
Reported by @LynnMcrae -- I find that when editing a page, all changes are ignored if I leave my cursor in a block of text I last edit. This includes additions, deletions and edits unrelated to my final changes. it nonetheless asserts that the update was successful and that changes were saved. If I tab out of an editing block before pressing save things seem to work ok. It was a very frustrating experience with exhibits since it initially seemed to be a random failure.

**Comment by LynnMcRae** [comment]
I was in Chrome if that makes a difference.
