### ISSUE TITLE
Project now requires Ruby 2.4

### ISSUE THREAD

**Issue by ncaramello** [projectblacklight/spotlight#1775]
As of the latest version of github-markup this project now needs Ruby 2.4.  Either a specific version of github-markup needs to be specified, or the documentation needs to be updated to reflect the 2.4 requirement.

Ruby 2.4 is not available on windows.

**Comment by cbeer** [comment]
Are you sure it is a `github-markup` requirement, or is coming from one of their dependencies? I ask because their travis file claims they test ruby 2.0+, so maybe this is something that can be resolved upstream.

**Comment by ncaramello** [comment]
well, yes, it is a downstream requirement - github-markup uses the linguist gem, unspecified version.  the latest version of the linguist gem uses rails 5.0.2, etc. 

I guess I'd put it this way - if you get the spotlight repo, and build it as is, it requires ruby 2.4, and wont build on windows. if you want it to build as is using ruby 2.2, I think you have to specify a version of github-markup that does not use (an unspecified version of) linguist.  

you may not consider this a bug, and I've addressed this locally, so.....

**Comment by jcoyne** [comment]
@ncaramello couldn't you put a working version of linguist in your Gemfile?

e.g.:
```ruby
gem 'linguist', '~> 3.2'
```

Does that fix the problem?

**Comment by cbeer** [comment]
I'm not seeing a dependency on `linguist` and our ruby 2.3.3 build works fine. Maybe they've done something upstream to avoid it?

**Comment by ncaramello** [comment]
Hmmm.  I may be missing something.  If so, please close.  That said

https://github.com/github/markup/commit/179819e484f59b1ef07f343d4e5a124e7d537caf

look in markdown.rb.

**Comment by jcoyne** [comment]
@ncaramello what are we supposed to be looking for?  the `Linguist` constant?  That's defined in `github-lingust` a gem that is not the same as the `linguist` gem

**Comment by ncaramello** [comment]
@jcoyne, not sure that it matters how linguist is pulled in. if you pull the spotlight project and build it, right now, it will try to install the latest linguist gem, which requires Ruby 2.4.  

if a goal of this project is to have users use it without having to add requirements to their gemfile (and spend time working out why they have to do so), and/or to run without modification against Ruby 2.2, then, unless I've missed something, this is something that should be resolved in this project, and not locally.

but, perhaps I'm missing something. or, if you just want to close this issue, do so.  

out.

**Comment by jcoyne** [comment]
@ncaramello we just built it successfully 1 hour ago on ruby 2.3.  It is not requiring linguist for us.  It pulls in github-markup 1.4.4. https://travis-ci.org/projectblacklight/spotlight/jobs/211937534#L256

**Comment by jcoyne** [comment]
We are building with Rails 4.  Are you using Rails 5?

**Comment by ncaramello** [comment]
I am building with Rail 5.0.2.  

I am just pulling the gem, and installing dependencies, without making any modifications.  That results in Rails 5.0.2 on my system (and 1.4.7 of github_markup)

I'm building on both Ruby 2.2 and 2.3 (2.3 does not really work on windows, but that's a separate issue)

**Comment by jcoyne** [comment]
`github-markup` changes its dependency on `activesupport` after 1.4.4, so that might be why our build works and yours doesn't.  @ncaramello Would you like to put in a PR to test spotlight on Ruby 2.3 + Rails 5?

**Comment by ncaramello** [comment]
I can, but it will be in the context of a project I am doing that wont start for a little while.

**Comment by mejackreed** [comment]
I'm seeing this now build successfully on Rails 5 and Ruby 2.3.4. Is this issue still relevant? @ncaramello any luck on Windows?
