### ISSUE TITLE
Curator change to metadata field label doesn't propagate to sidebar on home page (old label displays)

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1778]
For https://exhibits.stanford.edu/time-travel-japan -- curator changed metadata field label of "Donor tags" to "Prefecture". Sidebar on home page still displays with field label "Donor tags". (I tried reindexing all items, in case that matters or is connected, and the reindexing didn't correct the problem.)

**Comment by cbeer** [comment]
Facet field labels are configured separately from the display label. You can find the facet configuration here:

https://exhibits.stanford.edu/time-travel-japan/search_configuration/edit

**Comment by caaster** [comment]
Awesome thank you, @cbeer. Closing.
