### ISSUE TITLE
Improved password security

### ISSUE THREAD

**Issue by randystern** [projectblacklight/spotlight#1790]
Spotlight logins are vulnerable to hacking. The Spotlight user account creation accepts weak passwords, and also has no check for repeated login attempts - a bad combination since it exposes the system to a simple brute force attack. It would be good if both those were fixed. For example secure password guidelines, see Harvard's at http://reference.iam.harvard.edu/quick-guide-passwords .

**Comment by jkeck** [comment]
@randystern we use the [Devise gem](https://github.com/plataformatec/devise) for authentication in Spotlight (and try not to make too many assumptions about authentication given that people are likely to adopt their local institution's authentication system).

Devise has a handy [document](https://github.com/plataformatec/devise/wiki/How-To:-Set-up-simple-password-complexity-requirements) about setting up pasword complexity if a Spotlight implementer wishes to do so.

**Comment by randystern** [comment]
Thanks. I notice that there ia an extension for devise, https://github.com/phatworx/devise_security_extension that adds better password security. Would it make sense for the Spotlight team to incorporate this in the base software?

**Comment by mejackreed** [comment]
@randystern My feeling here is probably not with code, but perhaps better documentation. Its not that we don't want adopters to follow best practices, its that we don't want to make assumptions on how they are going to integrate devise. For instance, at Stanford we have no user local signup and we just integrate user accounts through our campus single sign-on. We follow this same pattern with other Blacklight applications (SearchWorks, GeoBlacklight, etc.).

I think most of the time we have assumed (perhaps incorrectly) that adopters will be using an external authentication. Maybe we can look at creating a wiki page on integrating or enhancing security for authentication and authorization?

**Comment by randystern** [comment]
What you say makes sense. In a rush to deploy things, in this case with a limited consulting budget, we sometimes defer the proper integration with on-campus login and go with the out-of-the box option. So in fact it is "temporary" - although that can last a while...
