### ISSUE TITLE
When logged out, when you click view button URL is updated but view is not

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1792]
Go to any exhibit browse category. View the category (which will be the default view). Attempt to change to a different view. This only works if you are logged in. When you are not logged in, when you click a different view button, the URL is updated but the view is not.

**Comment by mejackreed** [comment]
Can you add a public link where this is happening for you? I'm unable to recreate the problem logged out.

**Comment by caaster** [comment]
Gremlins (can't reproduce it today). When I sat with @jkeck yesterday, we both experienced this with the Stanford Band exhibit. For privacy reasons, we've had to temporarily unpublish the Stanford Band exhibit, so I'm not able to try and repeat the behavior there.

**Comment by mejackreed** [comment]
I think this must have been just a temporary glitch. I cannot recreate. Closing, feel free to reopen and comment if it starts happening again.
