### ISSUE TITLE
Uploaded Resources not indexing

### ISSUE THREAD

**Issue by travisLilleberg** [projectblacklight/spotlight#1797]
When I start a brand new Spotlight instance, I can't seem to get uploaded resources to index into solr. Whenever the reindex job runs, I get the following error:

`An error occured while reindexing. Contact your exhibits administrator for more information.`
<img width="910" alt="screenshot 2017-05-25 11 13 44" src="https://cloud.githubusercontent.com/assets/8809048/26457151/27c1a0be-413d-11e7-8b06-fca9de6c1b39.png">
I'm not seeing any errors in development.log

To reproduce:
1. rails new test_app -m https://raw.githubusercontent.com/projectblacklight/spotlight/master/template.rb
2. cd test_app
3. solr_wrapper
4. rails server
5. log in
6. create an exhibit 
7. create an item using "Upload Item" form
8. When it tries to reindex, it fails.

Perhaps I have something set up wrong, but from what I can tell, I'm using the defaults. I've thrown an extra `rake db:migrate` in there as well, but all the migrations have been run.

Thanks for any input.

EDIT: [Here's the log](https://gist.github.com/travisLilleberg/6c74b7f2e4016f9c8d0bf34abfe480f8).

**Comment by cbeer** [comment]
Can you look in the rails logs for more information?

**Comment by travisLilleberg** [comment]
Added development.log to initial post.

**Comment by jkeck** [comment]
@travisLilleberg are you saying that it doesn't index initially, or just re-indexing doesn't work?

Just want to make sure I have a handle on the issue.

**Comment by travisLilleberg** [comment]
It never indexes, either initially or on reindex.

**Comment by travisLilleberg** [comment]
Digging deeper, debugging the actual Rsolr client, I'm getting the error: 
`Faraday::Error: "solr" is not registered on Faraday::Adapter`


Full byebug response when I just try to run a blacklight_config.update call:
```
(byebug) blacklight_solr.update 
*** NoMethodError Exception: undefined method `response' for #<Faraday::Error: "solr" is not registered on Faraday::Adapter>
Did you mean?  respond_to?
```

**Comment by cbeer** [comment]
Ah ha -- it sounds like spotlight isn't compatible with RSolr 2.x. Can you try pinning to `rsolr ~> 1.0` in your application?

I think this is the culprit:

https://github.com/projectblacklight/spotlight/blob/a2a24e93b41ea2a1ab45914fc2240c66a7d95f68/app/models/spotlight/resource.rb#L70

and it needs to look something like:

https://github.com/projectblacklight/blacklight/commit/eb79e9f2ef238c0082ad3d99d3f216f3818428a5#diff-76707bae5367b57657dbb81b88df31e5R55

**Comment by travisLilleberg** [comment]
That took care of it! Thank you.
