### ISSUE TITLE
Migrating from Pre-IIIF exhibit thumbnails to IIIF thumbnails

### ISSUE THREAD

**Issue by travisLilleberg** [projectblacklight/spotlight#1801]
Hello,

I'm currently upgrading our Spotlight instance to the newest version, but I'm coming from a version that is pre-IIIF generated exhibit/browse page thumbnails, so they don't work anymore post upgrade.

When I try to re-choose the thumbnails via the GUI I get the following error.
`The image source must be a IIIF image. Contact your exhibits adminstrator or see the IIIF website for more information about IIIF.`

Is there any way to translate the uploaded images to IIIF images so that they'll work as exhibit thumbnails again?

**Comment by jkeck** [comment]
Hi @travisLilleberg,
We have a rake task that can update the items that were uploaded to an exhibit (via the Add Items UI):  `rake spotlight:migrate_to_iiif`

If you're talking about items that you've indexed into the exhibit using a custom resource indexer, that might be a little more involved (but happy to talk through it).

**Comment by travisLilleberg** [comment]
They are custom resources, so I'd rather not migrate them to IIIF. Does spotlight not support thumbnails from anything besides IIIF now?

**Comment by travisLilleberg** [comment]
This is no longer an issue for me, specifically, and it doesn't appear to be an issue for others so I'm just gonna close this down.
