### ISSUE TITLE
Search results widget displaying cut-off image thumbnails for slideshow view

### ISSUE THREAD

**Issue by caaster** [projectblacklight/spotlight#1803]
I expect the thumbnail pane to be filled by an entire thumbnail image.

<img width="816" alt="screen shot 2017-06-23 at 6 43 37 pm" src="https://user-images.githubusercontent.com/3210225/27504695-f69c14ba-5843-11e7-8a36-6a82a3f08f1e.png">

**Comment by anarchivist** [comment]
Perhaps a different manifestation of the same problem:

![screen shot 2017-10-10 at 2 28 37 pm](https://user-images.githubusercontent.com/73732/31411720-5b3d505e-adc7-11e7-81f5-42855a919362.png)

**Comment by ggeisler** [comment]
I believe the issue originally reported (images not filling the 100x100px square allocated for them) was fixed sometime back. Here's how the same page looks now:

<img width="609" alt="cape_of_good_hope___maps_of_africa__an_online_exhibit_-_spotlight_at_stanford" src="https://user-images.githubusercontent.com/101482/36220712-e13205e6-1178-11e8-9017-7d8656e73243.png">

I also checked how the slideshow page looks for a bunch of other SUL exhibits and they all fill in the thumbnail square (except when the image is much wider than it is tall; only saw that once though), as does a basic local version using Spotlight master.

The example @anarchivist posted above is thus working as expected with our current approach; I believe we get a 400px (with IIIF, such as in SUL Exhibits) or a thumbnail image (if no IIIF) and then center it in the 100x100 square, so the images usually looked fairly zoomed in (this approach ensures non-square images fill the thumbnail box except when the image height and width are very far apart).

However, I agree the result is not very agreeable. The zoomed-in result often doesn't help the user understand what most images are about and in many cases looks like there is some error in the loading of the images (e.g., two of the thumbs in the DLME example are basically blank).

I wonder if we considered using `object-fit: cover;` for these thumbnail images? If we didn't discard that approach for a good reason, I think it's worth considering. We already use that approach in a couple of places, such as the Curation > Items table that shows a thumbnail of each item. As an example, with `object-fit: cover;` the Maps of Africa example would look like this:

<img width="610" alt="cape_of_good_hope___maps_of_africa__an_online_exhibit_-_spotlight_at_stanford 2" src="https://user-images.githubusercontent.com/101482/36221349-0f079e48-117b-11e8-9dd0-423ba61734f0.png">

And the DLME example like this:

<img width="306" alt="thumbnail__yes_-_digital_library_of_the_middle_east_-_dlme_search_results" src="https://user-images.githubusercontent.com/101482/36221432-535982d2-117b-11e8-851c-08b05d11e7b9.png">

These are more visually appealing and provide more info to the user than our current approach.

**Comment by jkeck** [comment]
This is styled in the Blacklight-gallery gem.  I wonder if this is something we should improve upstream?

**Comment by ggeisler** [comment]
Seems like it to me, but I might not fully understand the implications. (I guess we'd potentially be changing how the slideshow looks in contexts other than Spotlight, which might be reason to hesitate, but on the other hand I'm not sure the current styling would be preferable in any context?)

**Comment by ggeisler** [comment]
Submitted a version of this suggested fix to the blacklight-gallery repo: https://github.com/projectblacklight/blacklight-gallery/issues/50

**Comment by mejackreed** [comment]
Spotlight adopters wanting the fix here should update blacklight-gallery to at least v0.10.0
