### ISSUE TITLE
How to add new Sir Trevor block to widget menu

### ISSUE THREAD

**Issue by travisLilleberg** [projectblacklight/spotlight#1804]
Hello,

I'm trying to add a "Subheading" block to the Sir Trevor widget options, which is the same as heading, except that it uses h3s instead of h2s. I'm following the instructions on [the wiki](https://github.com/projectblacklight/spotlight/wiki/Page-widgets).

I can see it's being loaded into the SirTrevor.Blocks, it's just not showing up in the widget icons when someone makes a new block.
![blocks](https://user-images.githubusercontent.com/8809048/27696082-b7b8fd38-5cbe-11e7-96a7-da77519870fa.png)

I've chased the issue down to line 21 in javascripts/spotlight/sir_trevor/block_controls.js

```javascript
 function generateBlocksHTML(Blocks, availableTypes) {
    var groups = {};
    for(var i in availableTypes) {
      //. . . . etc
```
It seems my 'Subheading' block is not in the availableTypes array, so it's not being loaded. 

So my question is, how can I get it into availableTypes? Have I set up my view/model/js wrong? I'll attach my files at the bottom.

Thanks for any help,

-- Travis

**app/assets/javascripts/spotlight/blocks/subheading_block.js**
```js
SirTrevor.Blocks.Subheading = (function() {

  return SirTrevor.Block.extend({
    type: "subheading",

    title: function() { return "hi!" },

    icon_name: "tweet", //Just for testing, will make an icon later

    formable: true,

    editorHTML: function() {
      return _.template(this.template, this)(this);
    },

    template: '<input type="text" name="title" />'

  });
})();
```

**app/views/spotlight/sir_trevor/blocks/_subheading_block.html.erb**
```ruby
<h3><%= subheading_block.title %></h3>
```

**app/models/sir_trevor_rails/blocks/subheading_block.rb**
```ruby
module SirTrevorRails
  module Blocks
    ##
    # Display a subheading
    class SubheadingBlock < SirTrevorRails::Block
      include Displayable
      include Textable

    end
  end
end
```

**Comment by cbeer** [comment]
I think `availableTypes` comes out of this list:

https://github.com/projectblacklight/spotlight/blob/37f6a4c266db9aa9d2a59529340a634d1796fefc/app/assets/javascripts/spotlight/pages.js.erb#L25

**Comment by travisLilleberg** [comment]
Yes, adding it to that list took care of it. 

Thank you.

**Comment by travisLilleberg** [comment]
I've discovered a new wrinkle to this. 

The way pages.js.erb is written, you can't access/change the array of blockTypes or the editor object itself. So I overwrote the entire file in my application, which works on local. Unfortunately, the asset pipeline doesn't do javascript asset overrides, so on my production server both files get compiled and the code runs twice, breaking the interface.

I'm still looking into the best way to deal with this, any advice is appreciated. Thanks.

-- Travis

**Comment by mejackreed** [comment]
I haven't looked at this in a while @travisLilleberg but what do you think about this approach? https://github.com/projectblacklight/spotlight/pull/1781

**Comment by travisLilleberg** [comment]
I think that looks like probably the best way to handle this situation. Is there anything I can do to help with the process?

**Comment by mejackreed** [comment]
@travisLilleberg Its :shipit: now. Please take it for a spin to see if it works ok for you. Enhancements are welcome.
