### ISSUE TITLE
Facets not appearing

### ISSUE THREAD

**Issue by wwelling** [projectblacklight/spotlight#1812]
Added several metadata controlled vocabulary and enabled and saved the facets. Still none appear.

**Comment by randystern** [comment]
I have the same issue in my Harvard instance, and our developer Dee Dee Crema is out this week. I suspect its caused by solr reindexing failing to run, so no facets are created.

**Comment by randystern** [comment]
So does that change need to be made to the Spotlight master branch catalog_controller.rb as well?

**Comment by jcoyne** [comment]
@randystern no changes need to be made if you've configured your facets in you solr config.  

If you want Blacklight to request the facets that you have configured on each request (potentially longer request URLs) you can add:

```ruby
config.add_facet_fields_to_solr_request!
```

in your CatalogController

**Comment by jcoyne** [comment]
There may have been a regression in f29c31f319bab9441770be71929d74d48c9bcd0d

**Comment by randystern** [comment]
Thanks for your help Justin. We can do that locally. Since Spotlight is intended to be multitenant, would you recommend that the standard Spotlight catalog_controller include the
config.add_facet_fields_to_solr_request!  ?

**Comment by jcoyne** [comment]
@randystern I don't know that I know enough to say.  It's all about how you want to make the trade offs.

**Comment by wwelling** [comment]
@jcoyne there seems to be an issue other than setting `config.add_facet_fields_to_solr_request!` in the catalog_controller.rb

I have deployed a vanilla spotlight release v1.1.0 and set the facet fields to be indexes. I am experiencing the following issue.

Add a metadata field as controlled vocabulary.

![screen shot 2017-11-29 at 9 37 49 am](https://user-images.githubusercontent.com/8352733/33389304-0b21e578-d4f8-11e7-9109-8168f73ae7b6.png)

![screen shot 2017-11-29 at 9 38 01 am](https://user-images.githubusercontent.com/8352733/33389315-145e68be-d4f8-11e7-8dc3-295650717e32.png)

Enable it under Search -> Facets

![screen shot 2017-11-29 at 9 38 14 am](https://user-images.githubusercontent.com/8352733/33389348-2ee786ca-d4f8-11e7-9ba6-9aa2166e2588.png)

After saving and navigating back. The facet disappears.

![screen shot 2017-11-29 at 9 38 30 am](https://user-images.githubusercontent.com/8352733/33389368-3ee22c56-d4f8-11e7-9897-f14a40e9740e.png)

The facets do not show up in the sidebar either.

**Comment by wwelling** [comment]
I have discovered that if I revert the changes on pull request https://github.com/projectblacklight/spotlight/commit/d11bc4e46086350f4946c3ac018d91b2950a2201, the issue goes away. The issue would not reveal itself until save changes is called from the Search Facets Configurations.

Calling https://github.com/projectblacklight/blacklight/blob/acf1bcc0e779b4dc83110b007f49bea20759728b/lib/blacklight/configuration/context.rb#L16 with the original of a facet field configuration, always seem to return false.
