### ISSUE TITLE
Migrate references column from Strings to integers

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#1827]
We no longer need strings after: https://github.com/projectblacklight/spotlight/pull/1815

This https://github.com/mbleigh/acts-as-taggable-on/issues/853 is forcing us to make the change.

So we no longer need this custom column: https://github.com/projectblacklight/spotlight/blob/7ab587601351e10a403b01770055c13b646b29cc/db/migrate/20140206152809_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb#L13

We can revert to:
https://github.com/mbleigh/acts-as-taggable-on/blob/f5222d8afaec1337a9d76b27fcc503a9125fc85d/db/migrate/1_acts_as_taggable_on_migration.rb#L17

**Comment by dunn** [comment]
Can https://github.com/sul-dlss/dlme/pull/227 be easily adapted for Spotlight?

**Comment by dunn** [comment]
Or would it be as simple as adding a new migration, like:
```ruby
class ChangeTypeOfTaggingsTaggable < ActiveRecord::Migration[5.2]
  def change
    change_column :taggable_id, :integer
  end
end
