### ISSUE TITLE
Add blacklight advanced search to the generator

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#1842]

**Comment by randystern** [comment]
Thanks for working on enabling advanced search!

**Comment by jcoyne** [comment]
I’m not sure this is something everyone wants. We certainly don’t for DLME. Why not leave it as a separate optional plugin?

**Comment by mejackreed** [comment]
The thought here is to add it as a soft dependency and certainly not required for Spotlight consumers. With all of the pieces that need to be configured that hook seemed to be like the best way to get it in.

**Comment by mejackreed** [comment]
Closing this for now, as we have decided to hold off of integration of advanced search into Spotlight core. There are some technical considerations for doing this as well as not needed feature sets in our current development work.
