### ISSUE TITLE
Add basic enable / disable for advanced search in admin UI

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#1844]

**Comment by jcoyne** [comment]
I suspect this is hard because advanced search is more tha just UI+controller. It mutates every search you do. Be warned.

**Comment by mejackreed** [comment]
Closing this for now, as we have decided to hold off of integration of advanced search into Spotlight core. There are some technical considerations for doing this as well as not needed feature sets in our current development work.
