### ISSUE TITLE
per_page not working

### ISSUE THREAD

**Issue by whisere** [projectblacklight/spotlight#1848]
already have 
        config.per_page = [10,20,50,100]
	config.default_per_page =10
	config.max_per_page = 100
under catelog_controller but they all return 10 items

in development log it has 
Solr query: {"qt"=>"search", "facet.field"=>[...., "exhibit_1_tags_ssim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["{!raw f=...}..."], "hl.fl"=>[], "rows"=>20, "fl"=>"*", "q"=>"*", "spellcheck.q"=>nil, "facet"=>true, "sort"=>"... asc"}
from
 Rails.logger.debug("Solr query: #{solr_params.inspect}")
and added
Rails.logger.debug("Solr response: #{solr_response.inspect}")
Solr response only have 10 items.

at the solr side, it did send off 20 items

**Comment by whisere** [comment]
turns out it is solr setting causing this:
change qt from search to /browse works in this case. 

config.default_solr_params = { 
      :qt   => '/browse',

**Comment by mejackreed** [comment]
Awesome glad you figured it out. Sounds like a solr configuration issue?

**Comment by whisere** [comment]
Yes it is to do with solr configuration.
