### ISSUE TITLE
Migration fails during installation, cannot get forward

### ISSUE THREAD

**Issue by verheyenkoen** [projectblacklight/spotlight#1859]
During my spotlight installation (as described in the README), migration fails with this error:

> Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: ...

The installation procedure continues but I can't create an administrator. If I skip creating an administrator, installation ends "successfully" but there's no way to run the application.

**Comment by cbeer** [comment]
Can you provide more context from around that error? I believe we addressed Rails 5.1 compatibility in spotlight with our 1.0 release.

**Comment by verheyenkoen** [comment]
A colleague of mine helped me find the answer. 2 migration files were missing the version number at the end of the first line. So installing without admin, applying the fix and then running `rake db:migrate` made it work for me.
