### ISSUE TITLE
solr_document_sidecars are persistent?

### ISSUE THREAD

**Issue by nicolasfranck** [projectblacklight/spotlight#1865]
I know that spotlight creates records in the table "spotlight_solr_document_sidecars" for every
solr document it want to index. 

But in case of an IiifHarvester resource, the manifests are reloaded from the internet, so in  fact the sidecars can be recreated after every "reindex"?

I'm wondering because I'm looking for a way to attach extra metadata to every solr document , but I'm not sure whether these document are really persistent. If its persistent, I can use the id from the sidecar as foreign key for e.g. an annotation, comment.

**Comment by cbeer** [comment]
Yes, they're persistent. Spotlight uses them internally for document -> exhibit tracking, tags, public/private toggling, and exhibit-specific fields.

**Comment by nicolasfranck** [comment]
ok thanks ;-)
