### ISSUE TITLE
rake db:migrate fails

### ISSUE THREAD

**Issue by librarymark** [projectblacklight/spotlight#1877]
Total ruby/rails newbie here - I am trying to just take a quick look at spotlight. I am following the steps to install it, and I run this:
` rails new spotlight -m https://raw.githubusercontent.com/projectblacklight/spotlight/master/template.rb`
And it seems to finish fine. Then I do the next step,
` rake db:migrate` 
(in the spotlight directory) and I get this:
DEPRECATION WARNING: Initializing a file resolver without setting the base path is deprecated and will be removed in Riiif 2.0. (called from new at /root/projects/spotlight/config/initializers/riiif.rb:1)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFriendlyIdSlugs < ActiveRecord::Migration[4.2]
/root/projects/spotlight/db/migrate/20180110155041_create_friendly_id_slugs.rb:1:in `<top (required)>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFriendlyIdSlugs < ActiveRecord::Migration[4.2]
/root/projects/spotlight/db/migrate/20180110155041_create_friendly_id_slugs.rb:1:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

What am I missing?

**Comment by camillevilla** [comment]
hi @librarymark! What version of Rails are you currently using?

**Comment by librarymark** [comment]
5.1.4

**Comment by jlicht** [comment]
I am seeing the same issue, also on Rails 5.1.4

**Comment by camillevilla** [comment]
Ah. Looks like we're missing Rails versions for two migrations: `devise_invitable_add_to_users.rb` and `create_friendly_id_slugs.rb`. Add a version number to the migration and run `rake db:migrate` again.
```
class CreateFriendlyIdSlugs < ActiveRecord::Migration[5.1]
```

Let me know if that works!

**Comment by jlicht** [comment]
That works

**Comment by jlicht** [comment]
@camillevilla Thanks for your help. 

I can edit the migration files after they're created, and successfully re-run `rake db:migrate`. However, since the migration failed, the installation process wasn't able to create the default admin user, and it's not clear to me what changes would be required in the database to make that happen. Any suggestions?

**Comment by camillevilla** [comment]
@jlicht No databases changes needed once you run the migrations. If you use the following rake task, you'll be prompted to create an admin user:
```
bundle exec rake spotlight:admin
```

**Comment by jlicht** [comment]
Thanks, that worked

**Comment by camillevilla** [comment]
@jlicht @librarymark I'll close this issue for now, but if you have any additional Spotlight questions, feel free to either:
- ping the #blacklight channel on the [code4lib Slack](https://code4lib.org/irc)
- post something on the [Blacklight Development Google group](https://groups.google.com/forum/#!forum/blacklight-development)
