### ISSUE TITLE
Highlight the current page in the admin/curator navbar 

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/spotlight#1905]
@mark-dce suggested figuring out some way to indicate the current page in the admin/curator side navbar to make it clearer which page you're on.

**Comment by ggeisler** [comment]
How about something like:

<img width="312" alt="curation_-_curation_-_browse___widget_test_-_blacklight" src="https://user-images.githubusercontent.com/101482/36229705-5ea5adae-1195-11e8-9a73-4de4e9db297d.png">

Which in a more styled application like SUL Exhibits would look like this:

<img width="309" alt="curation_-_curation_-_browse___herbert_matter__modernist_photography_and_graphic_design_-_spotlight_at_stanford" src="https://user-images.githubusercontent.com/101482/36229725-71078ce2-1195-11e8-8508-37691fd1aece.png">

This would involve adding a `selected` class to the `<li>` of the selected page in the nav, and then this CSS:

```CSS
.nav > li.selected > a {
  background-color: #eee; 
  font-weight: bold;
}
```
(where `#eee` is specified the same way as the current li > a:hover background color is specified)

So this just makes the selected page nav link have the same background color as the hover background color, but also makes the page title bold to distinguish it a bit more.

Obviously there are other possibilities, but this seems like the least opinionated way of doing it while still being a decent approach if the implementing application doesn't override the styling.
