### ISSUE TITLE
Enable curator to provide translations of general exhibit labels

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1914]
(Part of #1912, a larger feature aimed at providing multilingual exhibits.)

When an exhibit administrator has added a language (through the General > Languages tab, as described in #1911), exhibit admins and curators should see a Curation > Translations menu item.

When navigating to the Curation > Translations page, there should be five tabs, as shown in the mockup below. This ticket covers the General labels tab. The numbered sections below correspond to the numbered orange note indicators in the mockup. 

<img width="557" alt="translation-general" src="https://user-images.githubusercontent.com/101482/36701606-4714b1c8-1b11-11e8-8693-d0b3654964c0.png">

### 1. Language buttons

Each language that has been added to the Current Languages section of the Configuration > General page should be represented by a button here. On page load the first button should be selected and the tabs on the page reflect the state of translation (progress counts and any existing translated field values) for that language.

When the user clicks a different language button, the page looks similar but loads the state of translation for that language. For example, here the user has clicked the Spanish button, which has only had one field translated so far:

<img width="505" alt="translation-general-spanish" src="https://user-images.githubusercontent.com/101482/36701803-ed642bd0-1b11-11e8-9a25-ec2f8b705ef0.png">

### 2. Progress counts

To give admins and curators a quick understanding of the translation progress for the selected language, each tab includes a progress indicator for the fields associated with that tab. For example, the General labels tab contains seven fields that could potentially be translated. In the first mockup above, there are three completed Italian translations, so the tab includes `[3/7]` as a progress indicator. I suggest using `#686868` for the text color of the progress indicator (I don't think we're using that color anywhere, but it's the lightest gray that meets AA color contrast level; Bootstrap's muted gray is too light).

### 3. Translatable fields

Each field that can be translated is shown with a field label at left and then a visually grouped block consisting of an input field for the translated field value and a help block below the input showing the current field value in the default language. Inputs are blank if no translated value exists; if a value does exist for a field, it's shown in the input so it can be edited.

Styling: Bootstrap's `panel panel-body` styling could possibly be used as a basis for the visual grouping, but we'd want to add `background-color: #f5f5f5; padding-bottom: 0;` to it. The field value shown below the input could be done as a `help-block` but I'd add `color: #555555; padding-left: 12px;` for contrast and alignment (there are Bootstrap variables for some of those property values, I think).

### 4. Completed translated icon

To help the curator more easily see which fields have been translated, show a check icon (e.g. `.glyphicon-ok` in `#80BF77`) next to each field with a value, after the page is saved. In other words, when this tabbed page is saved, we'd reload the page, updated to show 1) checkboxes next to each field with a value, and 2) currently accurate progress indicator in the General labels tab title (e.g., "[3/7]".

**Comment by jkeck** [comment]
All of the sections in the `General` tab have been completed.  Closing this now, but feel free to re-open if we've missed something.
