### ISSUE TITLE
Enable curator to provide translations of metadata field labels

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1915]
(Part of #1912, a larger feature aimed at providing multilingual exhibits.)

When an exhibit administrator has added a language (through the General > Languages tab, as described in #1911), exhibit admins and curators should see a Curation > Translations menu item.

When navigating to the Curation > Translations page, there should be five tabs, as shown in the mockup below. This ticket covers the Metadata field labels tab.

The Metadata field labels tab should include every field that is shown on the Configuration > Metadata page, with a section heading for exhibit-specific fields, if there are any in the exhibit (if not, omit the section heading). The layout and styling of the fields should be very similar to the General labels tab; see #1914 for details.

<img width="460" alt="translations-metadata" src="https://user-images.githubusercontent.com/101482/36703552-61be1246-1b19-11e8-86b4-ccebdd4e8ade.png">

**Comment by camillevilla** [comment]
- Closed by #1959
- Merged into [i18n-🌝](https://github.com/projectblacklight/spotlight/tree/i18n-%F0%9F%8C%9D) feature branch for Spotlight v2.0.0
