### ISSUE TITLE
Enable curator to provide translations of search-related field labels

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1916]
(Part of #1912, a larger feature aimed at providing multilingual exhibits.)

When an exhibit administrator has added a language (through the General > Languages tab, as described in #1911), exhibit admins and curators should see a Curation > Translations menu item.

When navigating to the Curation > Translations page, there should be five tabs, as shown in the mockup below. This ticket covers the Search field labels tab.

The Search field labels tab should include every field that is shown in the three tabs of the Configuration > Search page, with a section headings for each tabbed page, as shown in the mockup below. The layout and styling of the fields should be very similar to the General labels tab; see #1914 for details.

The Field-Based Search Options section should show the editable fields on the Configuration > Search, Options tab. The Facets section should show the facet fields on the Configuration > Search, Facets tab. And the Sort Fields section should show the editable fields on the Configuration > Search, Results tab. 

<img width="451" alt="translations-search-fields" src="https://user-images.githubusercontent.com/101482/36703831-c1d7a5ce-1b1a-11e8-9f8d-289bf1c71a5e.png">

**Comment by camillevilla** [comment]
- Closed by #1956
- Merged into spotlight#i18n-🌝 for Spotlight v2.0.0
