### ISSUE TITLE
Enable curator to provide translations of browse category fields

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1917]
(Part of #1912, a larger feature aimed at providing multilingual exhibits.)

When an exhibit administrator has added a language (through the General > Languages tab, as described in #1911), exhibit admins and curators should see a Curation > Translations menu item.

When navigating to the Curation > Translations page, there should be five tabs, as shown in the mockup below. This ticket covers the Browse categories tab. The numbered sections below correspond to the numbered orange note indicators in the mockup.

<img width="459" alt="translations-browse" src="https://user-images.githubusercontent.com/101482/36704557-132d7b6c-1b1e-11e8-93d1-adac8684a5a6.png">

### 1. and 2. Column headers

The layout of the Browse categories tab is somewhat different from the General labels, Metadata field labels, and Search field labels tabs because the browse categories are very repetitive in terms of fields. They all have a title, and optionally a description and that's it (in terms of translatable fields). Also, since (in Stanford's experience at least) exhibits can have many browse categories but these often don't include a description, this layout is intended to only show what the translator is most likely to need to translate a bunch of browse categories efficiently.

The layout here is thus just two columns, where the first column (note 1 in the mockup) has a heading of "English language title", where "English" could in theory be whatever the default language of the exhibit is, although we might want to just hardcode English for now and deal with the possibility of a dynamic default language later.

The second column header (note 2 in the mockup) should reflect whatever the currently selected language is.

### 3. Browse category titles and inputs

Under the headers are rows of title/input pairs, where each title is the default language title of a browse category. 

### 4. Browse category description labels

If, and only if, a given browse category has a description value in the default language, show a Description label with a toggle icon as shown in note 4 of the mockup. In other words, if a given browse category does not have a description in the default language, we do not enable inputting a description in the translated language.

### 5. Browse category description translation
If there is a description in the default language, a translated description is still optional, but if the user opens the Description toggle an input for translation is shown like this:

<img width="466" alt="translations-browse-open" src="https://user-images.githubusercontent.com/101482/36704991-25a8fa6c-1b20-11e8-842d-d57c024dfb7c.png">

There is no save button associated with the description field; the user must use the Save changes button for the page to save the description. The user should be able to have open multiple description sections at the same time (open one, enter a description, open the next one, enter a description, etc. and then save the page to save all translations).

See #1914 for styling suggestions that can be used for the open description section and showing the checkbox icon for any fields that have been translated.

**Comment by anarchivist** [comment]
Merged into feature branch

**Comment by jkeck** [comment]
Closed by #1940
