### ISSUE TITLE
Add toggle for exhibit visitors to switch between languages

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1920]
After one or more languages beyond the default language have been added to an exhibit (i.e., #1911) exhibit users need a way to switch languages, like this:

<img width="375" alt="33725033-d5fd6e42-db25-11e7-95c3-f18a40bd4a0b" src="https://user-images.githubusercontent.com/101482/36807063-2a0e9a3e-1c7f-11e8-801b-e15902f89d58.png">

**Comment by jkeck** [comment]
Adding some Acceptance Criteria after a convo w/ @ggeisler:

- The toggle should only include locales that are published for users w/o any exhibit privs.
- The toggle should include all locales that have been added to the exhibit for users w/ any exhibit privs.
- The toggle should show the locale in its original language.
- The locales should be sorted alphabetically.
- The currently selected locale should not be in the drop-down

**Comment by jkeck** [comment]
Closed by #1930
