### ISSUE TITLE
"Unpermitted parameter: url" for uploading image

### ISSUE THREAD

**Issue by yanyufish** [projectblacklight/spotlight#1938]
Hi,

I got the following log when trying to add an image using "Upload item". Even though it displayed the message "Object uploaded successfully." in UI, the item cannot be found in the items page. Then I saw the "Unpermitted parameter: url" in the log. Is this the reason why the item didn't get imported? If so, how could it be fixed?

Thanks.

![screenshot 8](https://user-images.githubusercontent.com/18058881/37425119-a7410e00-2798-11e8-8221-93564f90ab10.png)

**Comment by jkeck** [comment]
I just tested this on the latest Spotlight, and while I ddi get an `Unpermitted parameter: :url` message in the log, that did not affect the ability to upload an item.

It may be worthwhile to test this using a different background job queuing framework (like sidekiq) as that may be able to give you some better logging capabilities from the job.

**Comment by yanyufish** [comment]
I am new to spotlight. Could you tell me how to use a different background job queuing framework and what's the current one? I see the image stored at spotlight/public/uploads/spotlight/featured_image/image, but not in solr.

**Comment by jkeck** [comment]
Here is some documentation you might find useful: http://edgeguides.rubyonrails.org/active_job_basics.html#backends

We use [`Sidekiq`](https://sidekiq.org/) regularly and it can run pretty easily locally.

**Comment by yanyufish** [comment]
After reading https://github.com/mperham/sidekiq/wiki/Active-Job, I am still not sure how to use sidekiq. Could you show me step-by-step?

**Comment by mejackreed** [comment]
@yanyufish see the section "Setting up Sidekiq" from https://ryanboland.com/blog/writing-your-first-background-worker/ and then configure your `config/application.rb` to use sidekiq (see first part of https://github.com/mperham/sidekiq/wiki/Active-Job#active-job-setup Active Job setup)

**Comment by yanyufish** [comment]
@jkeck @mejackreed Thank you. I could upload images on centos, but not on windows. Could you tell me what should I put in the perform function from the second link? Also, does it support uploading pdf or video using csv file?

**Comment by mejackreed** [comment]
You don't need to put anything in the `#perform` method unless you are writing a custom uploader. You really just need to set your adapter in the `config/application.rb` file.

**Comment by yanyufish** [comment]
https://ryanboland.com/blog/writing-your-first-background-worker/ is not accessible any more. And when trying to run "bundle exec sidekiq", the following is shown:
DEPRECATION WARNING: Initializing a file resolver without setting the base path is deprecated and will be removed in Riiif 2.0. (called from new at C:/Sites/spotlight1/config/initializers/riiif.rb:1)
>          m,
>          `$b
>     .ss,  $$:         .,d$
>     `$$P,d$P'    .,md$P"'
>      ,$$$$$bmmd$$$P^'
>    .d$$$$$$$$$$P'
>    $$^' `"^$$$'       ____  _     _      _    _
>    $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
>    `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
>           $$:         ___) | | (_| |  __/   <| | (_| |
>           $$         |____/|_|\__,_|\___|_|\_\_|\__, |
>         .d$$                                       |_|
> 
> Signal TTIN not supported
> Signal TSTP not supported
> Signal USR1 not supported
> Signal USR2 not supported
> 2018-03-22T22:24:47.022Z 16968 TID-chthk INFO: Running in ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
> 2018-03-22T22:24:47.022Z 16968 TID-chthk INFO: See LICENSE and the LGPL-3.0 for licensing details.
> 2018-03-22T22:24:47.022Z 16968 TID-chthk INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
> 2018-03-22T22:24:47.022Z 16968 TID-chthk INFO: Booting Sidekiq 5.1.1 with redis options {:id=>"Sidekiq-server-PID-16968", :url=>nil}
> Error connecting to Redis on 127.0.0.1:6379 (Redis::TimeoutError)
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:344:in `rescue in establish_connection'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:329:in `establish_connection'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:99:in `block in connect'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:274:in `block in info'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis.rb:273:in `info'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq.rb:114:in `block in redis_info'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq.rb:96:in `block in redis'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq.rb:93:in `redis'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq.rb:107:in `redis_info'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-5.1.1/lib/sidekiq/cli.rb:81:in `run'
> C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sidekiq-5.1.1/bin/sidekiq:12:in `<top (required)>'
> C:/RailsInstaller/Ruby2.3.0/bin/sidekiq:23:in `load'
> C:/RailsInstaller/Ruby2.3.0/bin/sidekiq:23:in `<main>'

**Comment by yanyufish** [comment]
Ok. It's caused by ImageMagick. It's running on Windows locally and looks like it has some issue for ImageMagick 7. The solution proposed by https://stackoverflow.com/a/41094852 solved my problem. Thank you again. @jkeck @mejackreed 

More info about ImageMagick on Windows: http://www.imagemagick.org/Usage/windows/
