### ISSUE TITLE
Sitewide Locale Switcher

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/spotlight#1952]
Should we enable a site-wide locale selection?

I believe the only place the Exhibit's description is shown to an end user is on the landing page that shows all exhibits. (It is available in the OpenGraph metadata for the exhibit itself in the `<head>` which can be picked up by search engines)

However, we are currently only showing the locale switcher when there is exhibit context since the exhibit admin chooses which languages should be available per exhibit. (cc: @ggeisler)

**Comment by ggeisler** [comment]
@jkeck My suggestion would be not to worry about a site-wide locale switcher until someone has a use case for it. The current Stanford i18n requirement is to enable curators of individual exhibits to provide translations and locale switching, but we don't have a requirement for (and I haven't heard any discussion about the usefulness of) locale switching at the site-wide level (exhibits landing page), which is what I think you're referring to.

It's true that without locale-switching at the site level there is no visible place where the exhibit description translation is used, but I'd suggest that's fine, it's still worth providing the place to translate it in a given exhibit, for consistency with all the other similar fields that can be translated, for the OpenGraph metadata, and so it's already there if we do enable site-wide locale switching at some point in the future.

**Comment by jkeck** [comment]
👍 we can open up a new issue down the road if we deem that necessary.
