### ISSUE TITLE
Update browse categories translations form to add description for all categories

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1963]
Suggest we update the Translations > Browse categories form to show the Description expand/collapse section for **each** browse category, not just the ones that have a description in the default language.

### Rationale

The translation form for Browse Categories matches the design in the original ticket. However, since then we made a sort of philosophical change (while refining the design of the pages translation approach). Whereas originally the idea was the curator should only be able to provide translations for text that existed in the default language, we're now looking at translations as more independent (e.g. the translated exhibit could have more page text or published pages than the default exhibit).

To be consistent with this approach I think we need to enable the curator to provide a Description translation for a given browse category even if that browse category has no description in the default language.

**Comment by jkeck** [comment]
Closed by #1970
