### ISSUE TITLE
Write a data migration of some sort (rake task?) for new page slug scope

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/spotlight#2003]
Broken out of #1988 

We're updating the scope of page slugs to include the locale (that way many pages in an exhibit can have the same slug as long as they have different locales) and this scope is stored in the database.  We should provide some code that can help people migrate to the version of Spotlight w/ internationalization support.

**Comment by camillevilla** [comment]
- Closed by #2020
- Merged into [i18n-🌝](https://github.com/projectblacklight/spotlight/tree/i18n-%F0%9F%8C%9D) feature branch for Spotlight v2.0.0
