### ISSUE TITLE
Add Spotlight translation and internationalization documentation

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#2006]

**Comment by mejackreed** [comment]
An initial take of this is in https://github.com/projectblacklight/spotlight/wiki/Translations . Feedback is most welcome.

**Comment by anarchivist** [comment]
Suggestion from 4/24 - once we think it's solid enough, add to configuration section of navigation for Spotlight wiki.

**Comment by cbeer** [comment]
🚢
