### ISSUE TITLE
Translations of about pages are not getting linked to consistently

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/spotlight#2057]
If I switch to another language (e.g. `pt-BR`) and navigate to the about pages, the pages end up loading in their default languages. This is a case where the original pages and the translations are both published.

![35qt6k6udf](https://user-images.githubusercontent.com/73732/39613775-ddf748bc-4f1e-11e8-8b68-f76dd46916f3.gif)
![xrlruzzrwg](https://user-images.githubusercontent.com/73732/39613784-0522c768-4f1f-11e8-8485-98d388ce6b4b.gif)

**Comment by mejackreed** [comment]
I'm not seeing this happen upstream in Spotlight, so I'm thinking this has to do with our path based language routing.
