### ISSUE TITLE
Figure out better terminology for the zpr button

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#2064]
Its not really clear what this means to me, and I wonder if our users know what it means

<img width="279" alt="screen shot 2018-05-10 at 10 22 06 am" src="https://user-images.githubusercontent.com/1656824/39883587-247c06e8-543c-11e8-9223-95c12ecba205.png">

**Comment by blalbrit** [comment]
I'm pretty sure none of our users know what the Zoom-Pan-Rotate viewer is, esp. when presented as "ZPR" - is that term being used just to distinguish it from Mirador or UV?

**Comment by ggeisler** [comment]
I believe this dates from the earliest versions of Spotlight, and we were probably more focused on the functionality than the label, but I agree it isn't very end-user friendly. (Also, in Stanford exhibits at least, I don't think this option is selected very often, the recent Parker example notwithstanding).

What about "Show in zoomable viewer"?

I think that conveys the basic idea that selecting the button will result in the object being displayed in a viewer that enables interaction/manipulation with the image, which is probably sufficient for the user to decide whether she wants to open it or not.

**Comment by cbeer** [comment]
Fixed by #2711?
