### ISSUE TITLE
Provide a way to extend the Page form attributes options

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#2075]
For a Spotlight adopter creating custom SirTrevor widgets, they may want to add additional data-attributes to the Spotlight Page form: https://github.com/projectblacklight/spotlight/blob/master/app/views/spotlight/pages/_form.html.erb#L6-L15

This came up in a pairing session on adding a Mirador Widget with @jkeck and @aeschylus

**Comment by jkeck** [comment]
Closed by #2078
