### ISSUE TITLE
fresh install

### ISSUE THREAD

**Issue by bsheaff** [projectblacklight/spotlight#2076]
Doing:
rails new app-name -m https://raw.githubusercontent.com/projectblacklight/spotlight/master/template.rb
cd app-name
rake db:migrate
solr_wrapper
rails server

When I try to create a new exhibit I get an error:
NoMethodError in Spotlight::ExhibitsController#create
undefined method `[]=' for nil:NilClass
Extracted source (around line #206):
 @changed_attributes[attrib] = old.to_s if old.sort != ActsAsTaggableOn.default_parser.new(value).parse.sort

My env:
 CentOS Linux release 7.4.1708 
 ImageMagick-6.7.8
 ruby 2.3.3p222 
 Rails 5.2.0
openjdk version "1.8.0_161"

**Comment by bsheaff** [comment]
I tested again and I could create an exhibit but only if leave the text box tag lists empty.

My tag list:
cat,feline
this caused the error above

**Comment by cbeer** [comment]
Until earlier this week, the `acts-as-taggable-on` gem (which provides that functionality) was not compatible with Rails 5.2. They just release v6 that hopefully will address the problems you ran into. Try running `bundle update` to get the latest version of their gem.

**Comment by mejackreed** [comment]
This should be resolved by the `acts-as-taggable-on` updates and the latest Spotlight updates. Please reopen if you are running into issues.
