### ISSUE TITLE
search box in 'Browse' tab ignores toggle

### ISSUE THREAD

**Issue by dunn** [projectblacklight/spotlight#2102]
In the Search settings for an exhibit, if you uncheck 'Display search box', then the search box on the exhibit's 'Home' tab disappears, but the search box on the 'Browse' tab does not.  This is because the latter partial is from Blacklight, which doesn't know about `@search.search_box?`.

Should the partial be overridden by Spotlight, or is there a cleaner solution?

**Comment by ggeisler** [comment]
I don't have a suggestion for a fix (I'm not a developer) but agree this is a bug that should be fixed. Good catch, @dunn.

The search box is hidden from about and features pages, as it should be, but still shows when you are on the browse landing or browse detail pages.
