### ISSUE TITLE
server stop after a few days

### ISSUE THREAD

**Issue by whisere** [projectblacklight/spotlight#2130]
after running rails server -p 3000 -d > log &, the system always stops after a few days. The process for Puma disappear,  running rails server again can start the server, but it is not easy to keep monitoring the process and restarting the server. Any idea much appreciated.

**Comment by mejackreed** [comment]
Hi @whisere, is this in a production deployment scenario?

**Comment by whisere** [comment]
Thanks @mejackreed Yes we will eventually go into production. I also tried -e production, but it didn't work. is there difference for the process with and without production? and development won't run for long?

**Comment by mejackreed** [comment]
I would recommend in a deployment scenario not using `rails server` and instead using something like [Passenger](https://www.phusionpassenger.com/library/dev/ruby/rails_integration.html) to manage your Rails application processes.

There are some helpful guides online about how to deploy Rails applications in production:
 - [Deploy Ruby On Rails](https://gorails.com/deploy/ubuntu/18.04)
 - [How To Deploy Ruby on Rails Apps To The Internet](https://medium.com/ruby-on-rails-web-application-development/how-to-deploy-ruby-on-rails-apps-to-the-internet-production-staging-49efc503c91d)

We usually use the `rails server` command for local development use.

**Comment by whisere** [comment]
Thank you! @mejackreed I will try them.

**Comment by camillevilla** [comment]
Closing this for now. @whisere please feel free to open a new issue if you have more questions about Passenger.
