### ISSUE TITLE
Migrate off of Glyphicons

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/spotlight#2230]
- [x] glyphicon-plus-sign -> [add_circle](https://material.io/resources/icons/?search=add&icon=add_circle&style=sharp)
- [x] glyphicon-minus-sign -> [remove_circle](https://material.io/resources/icons/?search=remove&icon=remove_circle&style=sharp)
- [x] glyphicon-resize-small
- [x] glyphicon-fullscreen
- [x] glyphicon-exclamation-sign
- [x] glyphicon-ok-sign -> [check_circle](https://material.io/resources/icons/?search=check&icon=check_circle&style=sharp)
- [x] glyphicon-ok -> [check](https://material.io/resources/icons/?search=check&icon=check&style=sharp)
- [x] glyphicon-alert -> [warning](https://material.io/resources/icons/?search=alert&icon=warning&style=sharp)
- [x] glyphicon-remove-circle -> [remove_circle_outline](https://material.io/resources/icons/?search=remov&icon=remove_circle_outline&style=sharp)
- [x] glyphicon-search -> [search](https://material.io/resources/icons/?search=search&icon=search&style=sharp)
- [x] glyphicon-chevron-left -> [chevron_left](https://material.io/resources/icons/?search=chevron&icon=chevron_left&style=sharp)
- [x] glyphicon-chevron-right -> [chevron_right](https://material.io/resources/icons/?search=chevron&icon=chevron_right&style=sharp)
- [x] glyphicon-info-sign -> [info](https://material.io/resources/icons/?search=info&icon=info&style=sharp)
- [x] glyphicon-edit -> [edit](https://material.io/resources/icons/?search=edit&icon=edit&style=sharp)

**Comment by ggeisler** [comment]
I think we can find satisfactory equivalents for all of our Glyphicon icons in the MUI icon set, which is open source and familiar, etc. So unless anyone sees a reason not to, I suggest we go with MUI for the replacements.

I'm going to update @cbeer's list of Glyphicons above with the recommended MUI replacements.
