### ISSUE TITLE
Thumbnails too large in several widget edit panels

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2264]
Part of #2224
In the following widgets, the thumbnails are shown too large:

- [x] Browse Categories
- [x] Saved Searches
- [x] Pages

The other widgets seem to have the correct size for the thumbnails.

<img width="939" alt="Screen Shot 2019-11-12 at 5 26 19 PM" src="https://user-images.githubusercontent.com/101482/68722475-d2d7f380-0572-11ea-8a2c-f8ef9fc8db90.png">

**Comment by mejackreed** [comment]
I've evaluated all three of these things. It seems like to me that maybe #2272 resolved this?
