### ISSUE TITLE
Widen search options select menu

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2273]
Part of #2224
I don't fully understand the details of how the BS4 upgrade affects certain components, but I wonder if there is a way to widen the search options select menu so that the label text is fully visible:

<img width="1152" alt="Screen Shot 2019-11-13 at 9 20 07 AM" src="https://user-images.githubusercontent.com/101482/68782823-3b68b400-05f7-11ea-9de9-464b1e298a90.png">

Ideally the select menu should widen to accommodate the width of any text label, but even when the viewport is resized to mobile and the menu and search input get full-width, the size of the select menu doesn't change, although there is additional horizontal space available.

<img width="499" alt="Screen Shot 2019-11-13 at 9 25 58 AM" src="https://user-images.githubusercontent.com/101482/68783064-a4502c00-05f7-11ea-9894-0653909dfbfa.png">

**Comment by cbeer** [comment]
As best I can figure, this is some weird artifact of the test app (perhaps related to loading multiple versions of the bootstrap stylesheet?). The DLME app doesn't seem to have this problem.

**Comment by ggeisler** [comment]
@cbeer Yep, I see that the issue doesn't exist in DLME so I'm fine with closing this, but not sure if you want to do that or keep it open to figure out what the problem is in Spotlight.

**Comment by cbeer** [comment]
I'm fine leaving it open (I mean, it is a bug), but I'll toss it out of the DLME work.

**Comment by ggeisler** [comment]
Closing since I no longer see the problem in any Stanford exhibit or in DLME, at any viewport width.
