### ISSUE TITLE
Text block for image-oriented widgets is always on right

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2276]
Part of #2224
It looks like the "Display text on" option for the image-oriented widgets is not being respected. I see the following behavior for these widgets, but I assume it probably holds for any other widgets where we off the "Display text on" option:

- Uploaded item row widget
- Item row widget
- Item grid widget

For these widgets, even if the option is set to "Left":

<img width="1042" alt="Screen Shot 2019-11-13 at 12 05 13 PM" src="https://user-images.githubusercontent.com/101482/68795504-5b57a200-060e-11ea-8f86-49478d27cf0e.png">

The text block is always displayed on the right:

<img width="929" alt="Screen Shot 2019-11-13 at 12 04 54 PM" src="https://user-images.githubusercontent.com/101482/68795693-b25d7700-060e-11ea-920a-5bc1c2107a73.png">

**Comment by cbeer** [comment]
It looks like bootstrap did away with the `push-` and `pull-` classes and we'll have to use their flexbox classes instead
