### ISSUE TITLE
Facet chevron icons in wrong orientation in default state

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2279]
In their default state (meaning they haven't been opened yet), the facet headers show their chevron icon in the orientation we typically use for an open facet:

<img width="301" alt="Screen Shot 2019-11-13 at 2 16 55 PM" src="https://user-images.githubusercontent.com/101482/68805222-96fb6780-0620-11ea-89b0-674f22c50f96.png">

If you do open a facet, the icon orientation is unchanged, which is appropriate for the open facet. And if you close an open facet, the chevron icon changes to the desired orientation for a closed facet.

So the issue appears to just be with facets that have not yet been opened.

**Comment by cbeer** [comment]
Fixed by https://github.com/projectblacklight/blacklight/pull/2209.
