### ISSUE TITLE
Update subject line of feedback submission form

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2282]
This is pretty minor since presumably Spotlight adopters will customize the Feedback email details for their institution, but in case they don't, it seems like it's worth updating the current subject line text from "Blacklight Contact Form" to "Spotlight Contact Form". 

I'd actually suggest "Spotlight Feedback" might be more appropriate, given the label of the form trigger is "Feedback" and not "Contact".

<img width="312" alt="Screen Shot 2019-11-13 at 3 43 41 PM" src="https://user-images.githubusercontent.com/101482/68810996-cc0db700-062c-11ea-8fc3-d098c84dd703.png">

**Comment by cbeer** [comment]
I don't think we can change "Blacklight"; it's coming out of the i18n key for the application name (which.. if it isn't set by the implementor, will show up plenty more places.). In #2284, I can make it use the configured site title if available though (which seems to be what we're doing other places in spotlight)
