### ISSUE TITLE
Browse category and Pages widget display issues

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2323]
There are multiple styling issues when rendering the Browse category and Pages widgets.

### Previous rendered view
This is a Stanford exhibit example, but I don't think we customized this beyond the base Spotlight version:
<img width="774" alt="Screen Shot 2019-12-06 at 3 44 00 PM" src="https://user-images.githubusercontent.com/101482/70361708-beb8a680-183f-11ea-8190-115e092824c5.png">

### Current rendered view
The example from the current code is displayed below using the same viewport width as above. Seems like we have multiple post-BS4 upgrade fixes to figure out:

- Title and count text placement
- Text color
- Tiles too tall (fixing might take care of next couple of items?)
- Spacing between category tiles
- Row extends past right-edge of page content area

<img width="782" alt="Screen Shot 2019-12-06 at 3 45 52 PM" src="https://user-images.githubusercontent.com/101482/70361899-67670600-1840-11ea-906a-d52f225b35bb.png">

Not surprisingly, the same issues as the browse category widget examples above occur with the pages widget:

<img width="785" alt="Screen Shot 2019-12-09 at 10 32 45 AM" src="https://user-images.githubusercontent.com/101482/70458517-6f58bd00-1a6f-11ea-98a4-758ccf3a6549.png">

**Comment by mejackreed** [comment]
@ggeisler Do we want this to look more like the previous work (text styled at bottom) or like the current browse page look (text styled centered)

<img width="1041" alt="Screen Shot 2019-12-09 at 2 32 31 PM" src="https://user-images.githubusercontent.com/1656824/70474945-c0c57400-1a90-11ea-9b6e-3f8992443eff.png">

**Comment by ggeisler** [comment]
@mejackreed I'd stick with the bottom approach. You could make an argument either way, but I believe the thinking behind the bottom alignment was to have reduce the impact of the text interfering with the image content.

I could probably be persuaded to go with center-alignment though.

**Comment by ggeisler** [comment]
I'm reopening this because I still see part of the problem that led me to open the issue originally.

At the `lg` (992px - 1199px) breakpoint, when the page has a sidebar, the tiles are too close together:

<img width="776" alt="Screen Shot 2019-12-18 at 2 05 46 PM" src="https://user-images.githubusercontent.com/101482/71123536-1e984100-21a0-11ea-9bd0-cbe022649022.png">

Here's how they used to, and should look:

<img width="752" alt="Screen Shot 2019-12-18 at 2 05 34 PM" src="https://user-images.githubusercontent.com/101482/71123563-2eb02080-21a0-11ea-90f9-a202df811970.png">

It also appears that the title/item count label is not quite centered horizontally (in the first example above, compare the distance from the left-edge to  "3300" and the distance from "BCE" to the right-edge).
