### ISSUE TITLE
Thumbnails on admin dashboard have too much space

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/spotlight#2339]
This might also exist elsewhere around the app.

---

<img width="860" alt="Screen Shot 2019-12-11 at 2 18 13 PM" src="https://user-images.githubusercontent.com/96776/70665294-20eb2000-1c21-11ea-84fc-d504456698b8.png">

**Comment by ggeisler** [comment]
Yeah, there are a lot of BS4-upgrade styling issues on the admin side. I've been holding off ticketing/fixing them until we get the DLME work cycle done, but am planning to work on those at some point (not that you and others shouldn't ticket them in the meantime).

**Comment by mejackreed** [comment]
I wonder if this particular issue is now fixed. I wasn't able to recreate it

<img width="1002" alt="Screen Shot 2019-12-13 at 3 18 05 PM" src="https://user-images.githubusercontent.com/1656824/70835913-cf2acd00-1dbb-11ea-955f-09b04da9ceee.png">

**Comment by jkeck** [comment]
Odd.  This is what I see on a master locally:
<img width="863" alt="Screen Shot 2019-12-13 at 6 17 20 PM" src="https://user-images.githubusercontent.com/96776/70842125-e0cc9e80-1dd4-11ea-9fdf-b69286230526.png">

And DLME, which is running on master has:
<img width="848" alt="Screen Shot 2019-12-13 at 6 18 07 PM" src="https://user-images.githubusercontent.com/96776/70842145-f17d1480-1dd4-11ea-9e46-78a99fc648a1.png">

**Comment by jkeck** [comment]
@mejackreed I think the reason you may have been seeing something different is it that this may be browser specific and probably has something to do with how the 4.0 flex style column widths play with table elements.  The Bootstrap documentation doesn't mention sizing columns, but this generally seems to work out (and should be more consistent across browsers)
