### ISSUE TITLE
Indexing some IIIF content is causing errors

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/spotlight#2365]
https://purl.stanford.edu/sp662qh5989/iiif/manifest

```
Error performing Spotlight::ReindexJob (Job ID: e32d2ad9-0e5a-402c-a3e0-10c625cd4bb5) from Async(default) in 327.59ms: NoMethodError (undefined method `has_key?' for #<Array:0x00007fd4e29faab0>):

.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:202:in `from_ordered_hash'
```

**Comment by jkeck** [comment]
As of right now, I don't believe Spotlight claims to be able to handle every permutation/flavor of metadata that could be returned by a IIIF Manifest.  Spotlight provides an abstraction for a downstream consumer to provide code to process the flavors of IIIF that they're interested in dealing with.

Now that the spec has settled some (and there are some better libraries in the wild for dealing with IIIF content) this might be worth revisiting, but at the moment, it does not surprise me that Spotlight is not able to process any IIIF manifest in the wild (as that was not our goal w/ the original implementation)

**Comment by mejackreed** [comment]
Got it.. hadn't realized that. I'll close this issue until we have a better understanding of what we intend for this.
