### ISSUE TITLE
Curation > Contacts card info needs more horizontal space

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2419]
On the Contacts card, the contact info (name, title, etc.) doesn't seem to extend to the right to prevent text wrapping, even when there is plenty of horizontal space available. For example, in the screenshot below, in the first card the "Green Library at Stanford" wraps, and in the second card the name value wraps:

![Screen Shot 2020-02-10 at 2 59 06 PM](https://user-images.githubusercontent.com/101482/74198458-47740a00-4c16-11ea-8b01-469258b0cd59.png)

Also, the layout of card elements would feel more consistent if the checkbox was aligned horizontally with the drag icon to its left (and the Edit Delete links on the right side of the card).

**Comment by mejackreed** [comment]
I'm only seeing this at the small and xtra-small screen sizes on Firefox, but it seems that the Chrome behavior is different.
