### ISSUE TITLE
Landing page card back description truncated unnecessarily at XL viewport

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2443]
As part of the BL7/BS4 update, the truncation strategy for the description text on the back of the landing page card changed. Because the landing page cards are larger at the `xl` viewport width than the `lg` and `md` viewport widths, there is more room on the card for the description text at the `xl` viewport width. Previously we adjusted the truncation so that more description text was displayed in the `xl` viewport:

![Screen Shot 2020-02-12 at 11 49 27 AM](https://user-images.githubusercontent.com/101482/74371940-980e7300-4d8e-11ea-8c6d-0fbf0af2a599.png)

As the example above shows, there is plenty of room to display the entire description on the card in the `xl` viewport width, but we're truncating it as if it were on the smaller, `lg` and `md` viewport width.

**Comment by jkeck** [comment]
Note, this is likely to be affected by the desired home page changes.  There are several issues w/ our current implementation that should probably be addressed, but w/o knowing what we'll eventually want, this ticket is not actionable.
