### ISSUE TITLE
YML import/export for languages by besides the default locale

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/spotlight#2516]
This is a follow-on task from #2509. Currently, the YML import / export feature in `Curation > Translations` only exports the application's default locale. In the `.internal_test_app`, this is set to English. It would be good to add the ability to export other locales.

**Comment by camillevilla** [comment]
hi @ggeisler! I'm working on cleaning up the implementation of this in #2520. My goal is to allow curators to export both the default locale file (English) and any other translations created through the Curation UI. Two applications I have for this:
- exporting existing Arabic translations in dev for sul-dlss/dlme for review and additional translation in Transifex
- exporting Curator UI text and creating an additional backup (i.e. GitHub, team drive, etc.) 

In this example (as #2520 is currently implemented), clicking on the "Export translations" button would export a Spanish locale file that included the exhibit title, `título de ejemplo`. 

![Screen Shot 2020-04-14 at 4 34 27 PM](https://user-images.githubusercontent.com/5402927/79284066-7e60d900-7e6e-11ea-97a0-335b911e59b2.png)

I hesitate to throw another button into the mix, but what do you think of something like this? 
![Screen Shot 2020-04-14 at 4 42 59 PM](https://user-images.githubusercontent.com/5402927/79284339-355d5480-7e6f-11ea-8fee-cc0a7792404c.png)

**Comment by ggeisler** [comment]
👍 Sure @camillevilla this looks clear to me.
