### ISSUE TITLE
Unable to upload images in containerized Spotlight

### ISSUE THREAD

**Issue by KingNoah** [projectblacklight/spotlight#2529]
I work at UT Austin, we're running into issues trying to upload single items and CSVs in our Docker containerized Spotlight instance. Acknowledging the fact that it may be our doing in how we've set up our container, the issue is nearly identical to issue #1807 from a few years ago. We're using ImageMagick 6.7.8-9, Riiif 2.3.0, and Spotlight 3.0.0.0.alpha.9. The images are being uploaded into `/public/uploads/spotlight/featured_image/image` and I have added the following to `config/initializers/riiif.rb`:

`Riiif::Image.file_resolver.base_path = '/public/uploads/spotlight/featured_image/image/'`

I get the following in the terminal when it errors out

`Spotlight::FeaturedImage Load (35.9ms)  SELECT  'spotlight_featured_images'.* FROM 'spotlight_featured_images' WHERE 'spotlight_featured_images'.'id' = 12 LIMIT 1`

`[ActiveJob] [Spotlight::ReindexJob] [690846dd-91ce-4145-9369-229372a7b4b6]   ↳ /usr/local/rvm/gems/ruby-2.6.5/gems/activerecord-5.2.4.2/lib/active_record/log_subscriber.rb:98`

`[ActiveJob] [Spotlight::ReindexJob] [690846dd-91ce-4145-9369-229372a7b4b6] Invalid characters in id '12'`

`[ActiveJob] [Spotlight::ReindexJob] [690846dd-91ce-4145-9369-229372a7b4b6] Error performing Spotlight::ReindexJob (Job ID: 690846dd-91ce-4145-9369-229372a7b4b6) from Inline(default) in 328.86ms: Riiif::ImageNotFoundError (Riiif::ImageNotFoundError):`

`/usr/local/rvm/gems/ruby-2.6.5/gems/riiif-2.3.0/app/resolvers/riiif/abstract_file_system_resolver.rb:18:in 'path'`

`/usr/local/rvm/gems/ruby-2.6.5/gems/riiif-2.3.0/app/resolvers/riiif/abstract_file_system_resolver.rb:11:in 'find'`

`/usr/local/rvm/gems/ruby-2.6.5/gems/riiif-2.3.0/app/models/riiif/image.rb:33:in 'file'`

`/usr/local/rvm/gems/ruby-2.6.5/gems/riiif-2.3.0/app/models/riiif/image.rb:53:in 'info'`

We have no problem uploading images locally, outside the container, using the same versions of ImageMagick, Riiif, and Spotlight. Any advice would be greatly appreciated!

**Comment by mgathu1** [comment]
hi @KingNoah,

We are also using docker, and to get the images working we used CarrierWaveFileResolver.
Here is how our config/initializers/riiif.rb looks like

```
Riiif::Image.file_resolver = Spotlight::CarrierwaveFileResolver.new
#Riiif::Image.file_resolver.base_path = '/public/uploads/spotlight/featured_image/image'
# Riiif::Image.authorization_service = IIIFAuthorizationService
Riiif.not_found_image = 'app/assets/images/us_404.svg'
#
Riiif::Engine.config.cache_duration = 365.days
```

FWIW, we had to downgrade to Spotlight 3.0.0.0.alpha.6.

**Comment by KingNoah** [comment]
Thanks for the comment @mgathu1, we're using Carrierwave as well. It turns out our issue was that we were using the Passenger app server in our container, we switched to using Puma instead and it seems to have fixed the issue
