### ISSUE TITLE
Update layout of Feedback (Report a problem) form

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2543]
Below are recommendations for updating the layout of the Feedback/Report a problem form. The basic design of the current form is six years old and when recently evaluating our feedback forms at Stanford we came up with some ideas for modernizing it a bit. These recommendations don't change the actual data that is posted from the form, just rearranges elements, renames labels, and adds a couple of elements.

<img width="1073" alt="Screen Shot 2020-07-14 at 4 07 23 PM" src="https://user-images.githubusercontent.com/101482/87487689-31b6a680-c5f3-11ea-90a6-ebbd50062009.png">

---

- [x] **A:** Change the gray background color to be the same as the `<body>` color (by default, `#fff` I believe)

- [x] **B:** Remove the form heading. Since the form opens immediately below the "Feedback" link that triggers it, it is likely very clear to user what the form is for without a heading.

- [x] **C:** Reorder the form fields and rename the "Name" and "Email" fields. So the updated name labeling and order is "Message", "Your name", and "Your email". The "Message" field could be reduced in height, as well.

- [x] **D:** Change the alignment of the action buttons to be left-aligned, "Send" and then "Cancel".

In addition to those changes, there are two recommended additions:

<img width="1040" alt="Screen Shot 2020-07-14 at 4 13 46 PM" src="https://user-images.githubusercontent.com/101482/87488077-40ea2400-c5f4-11ea-87db-de991e53a9fd.png">

---

- [x] **E:** Add a Bootstrap `alert-primary` component to the top of the form, which contains a string with the URL of the current page ("Reporting from: _current page URL_"). This helps the user understand that we know which page they're reporting from, so they don't have to include it in their feedback message.

- [ ] **F:** Assuming it's feasible to add a Captcha in Spotlight, versus having to add it in a localized repo (e.g., Stanford Exhibits), for non-logged-in users, add a Captcha. 

In the mockup the text below the Captcha says "(Stanford users can avoid this by logging in.)", which is obviously a localized string. The default string could be "(You can avoid this Captcha by logging in.)" so if an implementer forgets to localize it, it will still make sense to the user.

**Comment by cbeer** [comment]
Couple questions..

A) Do we  need a form background or some other divider for exhibits that haven't selected a masthead  image?

B) Should we keep the header  in non-js contexts? 

D) Just confirming we're ok with this being different  than the  rest of the  forms?

**Comment by ggeisler** [comment]
> A) Do we need a form background or some other divider for exhibits that haven't selected a masthead image?

I hope we don't actually have this scenario in a production exhibit, but you're right, we should do something just in case. I'd suggest adding (or replacing the existing bottom border styling) a `border-bottom: 1px solid #6c757d;` to the form container, where `#6c757d` is Bootstrap color variable `gray`. I think that will be unnoticeable when there is a masthead image, but will show a clear divider when there isn't.

> B) Should we keep the header in non-js contexts?

Good point. In no-JS the form is displayed as a dedicated page, separated from the Feedback trigger, so a visible heading would be helpful. I also didn't specify that we maintain the heading for `sr-only` but I think it makes sense that we do that, too, hopefully using the same heading. Rather than "Report a problem" I'd suggest we change the default text of the heading to "Feedback" to be more generic and not suggest that feedback has to be problem.

> D) Just confirming we're ok with this being different than the rest of the forms?

Yes, from a user point of view we're thinking of the form as more a part of the institution's feedback reporting than a part of the Spotlight application. This is a little SUL-centric in that the suggested changes match how we are trying to do SUL feedback forms consistently across our applications, but I think the Spotlight inconsistencies (mainly the alignment of the buttons, in terms of what a user would notice, I believe) are minor enough to justify that.
