### ISSUE TITLE
Odd rendering of Curation > Translations buttons - invalid Bootstrap code?

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2554]
When working on some other things in the code, I noticed that the relatively recently-added Curation > Translations, Import and export translations section displays buttons (when at the `lg` viewport width) with too much height. Basically the buttons are taking the full-height of the row they are in:

<img width="731" alt="Screen Shot 2020-08-07 at 4 20 25 PM" src="https://user-images.githubusercontent.com/101482/89695900-913e6400-d8ca-11ea-935f-769b372b1794.png">

Looking at the code, [this partial has several instances](https://github.com/projectblacklight/spotlight/blob/52148ad3763a0acf97f1eb388e801e1126350325/app/views/spotlight/translations/_import.html.erb#L2) where the Bootstrap `row` and `col` classes are used in the same div:

`<div class="row col-md-12 mb-4">`

I've never seen that before and am not sure if it is valid or not, but when I changed the initial instance of that to:

``` html
<div class="row mb-4">
  <div class="col-md-12">
  ...
```

It seemed to start to fix things. I was going to fix the whole partial in that way and submit a PR, but it started to get a little complicated (because one instance is done within a `bootstrap_form_for`) and I figured it might be done better by a developer who understands what's going on with this partial better than me.

Again, I'm not certain this is invalid code, but I've never seen buttons take the full-height of their row before and it seemed possible that it's related to the code structure.

**Comment by cbeer** [comment]
I think this is just flexbox doing its default thing when the label text wraps.  Tossing `align-items: ???` onto  the  container seems to fix it, but do you want the buttons centered on the label, aligned to the top, or something else?
