### ISSUE TITLE
Display published browse groups as filters on Browse landing page

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2567]
Related to #2562.

If an exhibit has no published browse groups, nothing (in terms of what the exhibit visitor sees) visibly changes from how the browse categories work today. The browse landing page looks and works the same way.

If an exhibit curator has added browse groups and published any of them, however, the browse landing page is affected.

By _affected_, I mean that filter buttons will be displayed at the top the browse landing page and selecting a filter button will change the browse categories displayed on the page. This is the same interaction as on the Spotlight _site_ landing page, where filter buttons can be used to display exhibits that match exhibit tags, and I suggest we use the same layout and styling (the styling in my browse group mockups looks different from the screenshot below because they reflect Stanford's Spotlight theme styling):

#### Spotlight site landing page

<img width="1152" alt="Screen Shot 2020-08-19 at 10 56 45 AM" src="https://user-images.githubusercontent.com/101482/90672286-be640e00-e20a-11ea-948f-e20a08c5e8f4.png">

---

#### Proposed browse landing page with published browse groups

<img width="1024" alt="Screen Shot 2020-08-19 at 10 45 59 AM" src="https://user-images.githubusercontent.com/101482/90674619-37b13000-e20e-11ea-8b80-2aee73825fde.png">

---

## Strategy for displaying browse group filters

- If at least one browse group is published and has at least one browse category assigned to it, display the filter buttons. (We could add the additional requirement that a published browse group must have at least one published browse category assigned to it, to prevent an empty result when that group filter is selected, but I'd suggest we keep it simpler and rely on the exhibit curator to know not to publish browse groups without assigned categories.)

- When displaying the filter buttons, always display an "All" filter first. The "All" filter is the default selection when navigating to the browse landing page without any query parameters that contain a specific filter value.

- The "All" filter displays all published browse categories in order, just as the browse landing page currently does.

- For each published browse group, display a filter button. The order of the filter buttons should follow the order of the browse group cards on the Curation > Browse page.

- When a browse group's filter button is selected, display only the published browse categories that are currently assigned to that browse group.

- The implementation should ensure that we can link to the browse landing page with a specific filter selected, as a query parameter (or whatever makes the most sense technically). This is probably necessary for a browse group widget, and the View action on the browse group card on the Curation > Browse page. We currently do this for the site exhibit tags, e.g.: `http://localhost:3000/spotlight/?tag=Installations`

## Example
This might not be necessary since the strategy here is so similar to the site exhibit tag filter but just in case:

Assume our exhibit's Curation > Browse page has this layout of browse groups and browse categories (note the unassigned category in the middle, and assume all groups and categories are published and there are a couple more groups and categories that complete the list):

- Group: Medium
    - Category: Paintings
    - Category: Calligraphy
    - Category: Graffiti
    - Category: Ceramics
    - Category: Drawings
- Category: Chinese influences
- Group: Time periods
    - Category: Work from the 1970's
    - Category: Work from the 1980's
- Group: Locations & Neighborhoods
    - Category: Brooklyn
...

---

The default display of the browse landing page would look like this (all published categories in order, ignoring their group assignment):

<img width="1024" alt="Screen Shot 2020-08-19 at 10 45 59 AM" src="https://user-images.githubusercontent.com/101482/90673891-33384780-e20d-11ea-8e4a-3c32a920de38.png">

---

If the exhibit visitor selected the "Medium" button, that button is shown as selected and only the five categories assigned to that group are displayed:

<img width="1031" alt="Screen Shot 2020-08-19 at 9 03 29 AM" src="https://user-images.githubusercontent.com/101482/90673942-49460800-e20d-11ea-8b13-431b8050d67f.png">

---

When selected, the "Time periods" filter would display only the "Work from the 1970's" and "Work from the 1980's" browse categories, etc.

**Comment by mejackreed** [comment]
Resolved in #2598
