### ISSUE TITLE
Update text of various messages related to browse group management

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2613]
PR #2608 added browse group administration. The feature itself works as intended, but there are a handful of flash messages and dialog text that should be updated.

(Some of these might seem like trivial updates but I have reasons for asking for them. I can explain my rationale if necessary...)

## Delete action label

<img width="761" alt="Screen Shot 2021-01-26 at 4 26 34 PM" src="https://user-images.githubusercontent.com/101482/105919675-4b4d9780-5ff3-11eb-8281-518b29fe9e7f.png">

Should be:

> Delete group

## Dialog displayed for confirmation when deleting a group

<img width="820" alt="Screen Shot 2021-01-26 at 4 01 54 PM" src="https://user-images.githubusercontent.com/101482/105919483-f6aa1c80-5ff2-11eb-9c8f-1993c60bc86a.png">

The text in the dialog should be:

> Are you sure you want to delete this browse group? (Browse categories associated with this group will not be deleted.)

## Flash message when creating a group

<img width="727" alt="Screen Shot 2021-01-26 at 4 00 11 PM" src="https://user-images.githubusercontent.com/101482/105919790-77691880-5ff3-11eb-885a-0635bd1c6a89.png">

Should be:

> The browse group was created.

## Flash message when editing browse group list 

When you save changes after re-ordering groups or changing the publish/unpublish checkbox:

<img width="727" alt="Screen Shot 2021-01-26 at 3 57 02 PM" src="https://user-images.githubusercontent.com/101482/105919997-d169de00-5ff3-11eb-8a8d-526cf72d7501.png">

Should be:

> Browse groups were successfully updated.

## Flash message when creating a new browse group

<img width="631" alt="Screen Shot 2021-01-26 at 4 00 11 PM" src="https://user-images.githubusercontent.com/101482/105920161-1d1c8780-5ff4-11eb-810a-289a32896f1d.png">

Should be:

> The browse group was created.

**Comment by jkeck** [comment]
@ggeisler should we keep the Add button as is or change it?

<img width="192" alt="Screen Shot 2021-01-29 at 11 14 58 AM" src="https://user-images.githubusercontent.com/96776/106317549-4ff89280-6223-11eb-8a8c-52d5f189d2b9.png">

**Comment by ggeisler** [comment]
@jkeck Do you mean change it to "Add new browse group"?

If so, no, I think it's fine as is. I know there's some inconsistency with referring to "group" and "browse group" in the main part of the page, but that's just to avoid unnecessary redundancy. I think the button label is clear without "browse group", given what's come before it. But in the flash message context I think it doesn't hurt to be specific about what was created.
