### ISSUE TITLE
Allow commas in tag labels?

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2755]
We have a curator who wants to create exhibit item tags that include a comma in the tag label. This isn't possible at the moment using the Edit item tags field, because the tags input treats a comma as a delimiter for multiple tags being entered at one time.

I thought a workaround might be to edit an existing tag (to add the comma) using the Curation > Tags edit-in-place functionality but it looks like a tag label update made in that fashion is silently discarded when a comma is included (i.e., after refreshing the Curation > Tags page, the tag label with a comma reverts to the previous version of the label).

I'm not sure if it's possible to update things so that a tag label with a comma is acceptable (even if it requires the Curation > Tags edit-in-place workaround) but it would help at least one curator use case (and perhaps more we don't know about or that will come up in the future).

**Comment by ggeisler** [comment]
Interesting. i might have missed that this approach also creates new tags for the parts after a comma. 

Still, the question is, is there a way where we can retain the edited version as a single tag, with the commas.

**Comment by cbeer** [comment]
This is not possible with our current tags implementation. The upstream gem splits on commas and we have no say in the matter.

**Comment by caaster** [comment]
Thank you @cbeer for the explanation. I put the ball back in Hannah's court to see if the stakeholder can suggest/live with alternative tags without commas.
