### ISSUE TITLE
Accessibility: Home Page - Link Purpose for exhibit card images

### ISSUE THREAD

**Issue by elrayle** [projectblacklight/spotlight#2767]
### Description

Site improve reports `Image link is missing alternative text` for all exhibit card images on the home page.

![image](https://user-images.githubusercontent.com/6855473/122931521-f82a0780-d33a-11eb-9bde-e11503cf6eb7.png)

### Solution

Short answer is to just add alt text to the link.

Options:
* set alt text to the exhibit title (e.g. Maps)
* set alt text to Exhibit + exhibit title (e.g. Exhibit Maps)
* set alt text to Exhibit + exhibit title for published exhibits (e.g. Exhibit Maps) and Unpublished Exhibit + exhibit title for unpublished exhibits (e.g. Unpublished Exhibit Maps)

**Comment by cbeer** [comment]
Card images are [decorative](https://www.w3.org/WAI/tutorials/images/decorative/)  (and the link and proposed alt text is already visible below), so I don't think it's appropriate to  duplicate that information here. I'm seeing the image+link properly marked up, such that this shouldn't be an issue (`aria-hidden` on the link, empty `alt` tag and `role="presentation"` on the image):

```
<a aria-hidden="true" tabindex="-1" href="/saytheirnames">
        <img class="card-img" alt="" role="presentation" src="/images/6866-1484bd4f7387a215cddaebeadeceaa65/307,15,1078,1078/400,400/0/default.jpg">
</a>
```

**Comment by elrayle** [comment]
I spoke with our local accessibility person.  The reason why SiteImprove complains about the missing alt text is that the information that provides the context is not within the same link tag.

[Example 2 from decorative docs](https://www.w3.org/WAI/tutorials/images/decorative/#decorative-image-as-part-of-a-text-link)
```
<a href="crocuspage.html">
	<img src="crocus.jpg" alt="">
	<strong> Crocus bulbs</strong>
</a>
```

`Crocus bulbs` can serve as the alt text because it is defined in within the `<a>` tag.

Spotlight code:
```
    <a aria-hidden="true" tabindex="-1" href="/test4">
        <img class="card-img" alt="" role="presentation" src="http://localhost:3000/images/42-8c53f78073c5a06a80b11a03b4ba4f81/0,0,252,252/400,400/0/default.jpg">
  </a>    
  <div class="card-img-overlay pb-0">
      <h2 class="card-title h5 text-center" aria-describedby="exhibit-description-test4">
        <a class="stretched-link" href="/test4">
          <span>test4</span>
        </a>
      </h2>
      ...
  </div>
```
The `<span>` which gives the title is associated with the second `<a>` and not with the image.

**Comment by cbeer** [comment]
Sorry for the delay. We were following up with our accessibility office to look into this. All indications on our end suggest the existing markup is appropriate and accessible in our version of SiteImprove and using e.g. JAWS and other assistive technology.

If you have a publicly available site, I can forward it to our accessibility group, since they're willing to take a look and maybe flag an issue for SiteImprove (especially if their tooling is giving inconsistent results...)

I think I said this, but maybe it was lost in slack history.. among other reasons, we're concerned that pulling the `<a>` tag up to surround the whole card will cause the link text to contain the subtitle + descriptions (and be unwieldy).

**Comment by elrayle** [comment]
Looks like we got caught between updates.  Our Siteimprove checks just switched to NextGen yesterday and now the error no longer exists.   I suspect other sites were already updated to NextGen checks for Siteimprove which caused the difference in reported errors.

Closing this since the latest Siteimprove does not see this as an error.
