### ISSUE TITLE
Clicking an out-of-date popup in the page editor can make it impossible to delete widgets

### ISSUE THREAD

**Issue by marrus-sh** [projectblacklight/spotlight#2811]
**Steps to reproduce:**

1. Add a standard text widget.
2. Type some text.
3. Select the text, and click either the heading or quote button in the popup which shows. The popup will remain visible after clicking the button.
4. Click either the heading or quote button again. (The option you choose here will not have an effect.)
5. Add a new widget.
6. Attempt to delete the new widget.

**Expected Results:**

The new widget can be deleted.

**Actual Results:**

The new widget cannot be deleted. There is an error thrown to the console: `Uncaught TypeError: can't access property "getAttribute", this.wrapper.querySelectorAll(...)[(blockPosition + 1)] is undefined`.

**Comment by taylor-steve** [comment]
I am unable to recreate this currently. I suspect the update to a newer version of Sir Trevor in Feb 2023 addressed this. Please feel free to re-open or start a new issue if this is still an issue for you.
