### ISSUE TITLE
the template.rb file used in README is not pointing to the correct branch

### ISSUE THREAD

**Issue by pengyin-shan** [projectblacklight/spotlight#2840]
Hi, I'm a new develper and I tried to create a spotlight app using the tutorial in README.md. I noticed that since the default branch is `main` instead of `master`, we need to add a branch name to `template.rb`, otherwise we will get an error from git in the creation process.

i.e.:
`gem 'blacklight-spotlight', ENV['SPOTLIGHT_GEM'] ? { path: ENV['SPOTLIGHT_GEM'] } : { github: 'projectblacklight', branch: 'main'}`

**Comment by taylor-steve** [comment]
Hi, thanks for reporting this. I believe this is resolved. Please feel free to re-open if you're still having the issue.
