### ISSUE TITLE
replace bootstrap-tagsinput dependency

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#2890]
https://github.com/mdbootstrap/bootstrap-templates/blob/2661784c2c281d3a69b93897ff3f39e4ffa5cbd1/package.json

The vendored version is 0.3.9.  We could upgrade https://www.npmjs.com/package/bootstrap-tagsinput

**Comment by jcoyne** [comment]
The mdbootstrap github repo seems to have been cleared and it now points at https://mdbootstrap.com/freebies/

**Comment by corylown** [comment]
Possible replacement? https://www.npmjs.com/package/bootstrap5-tags/v/1.7.2
