### ISSUE TITLE
 contact-email-delete relies upon rails-ujs

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#2910]
The link uses `remote: true` and there is code in exhibits.js that binding to ajax:success/error.  This is no longer supported because rails doesn't install rails-ujs by default.

**Comment by dnoneill** [comment]
waiting for propshaft to be the pipeline. Sprockets installs rails-ujs by default.

**Comment by dnoneill** [comment]
looks to be part of the propshaft branch
