### ISSUE TITLE
Specify config.search_state_fields for Blacklight 8

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#2966]
Blacklight 8 now sanitizes the search state parameters.  So we need to ensure some parameters that Spotlight uses are allowed.

```
    config.search_state_fields += [:exhibit_id, :browse_category_id]
```

**Comment by marlo-longley** [comment]
I can add the field to the search state, but I don't know the best way to verify this without being on BL8.

**Comment by marlo-longley** [comment]
Not sure the best way to test this without being on BL8, but the code change seems straightforward.
