### ISSUE TITLE
 Browse categories not updating

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#2968]
I’m getting some unexpected behavior using exhibit tags to make browse categories and want to check to see if this is a bug or if its how browse categories are supposed to work.

    I tagged 55 items with the “qalaat-seman” tag
    then built a browse category from all records with the “qalaat-seman” tag
    then I tagged more records with the “qalaat-seman” tag

I was expecting the browse category to include these new records but it doesn’t. I then manually selected the linked tag from one of the records which led back to a search result of all records with that tag. I tried to "update the existing category" from those results but the category was not updated.

This seems to resolve after clearing the rails cache, so there seems to be some place where we aren't poisoning the cache.

Moved from https://github.com/sul-dlss/dlme/issues/1753

**Comment by taylor-steve** [comment]
I cannot seem to recreate this, perhaps this has been fixed in the interim. It'd be appreciated if another dev could try and confirm/deny.

**Comment by hudajkhan** [comment]
@taylor-steve I tried this out and browse categories also worked for me correctly when I had made the categories public. 
Steps:
I added the tag "qalaat-seman" to four items in the exhibit, did a search for that tag, saved the search, went to the curation admin interface and selected browse, added the search as a browse category.  I looked at the page for that browse category independently and could see the items. I added the browse category widget to a page and could see the items (once that category was made public).  I added the tag to two more items and could see those items in the various pages as well.  Screenshots for the pages after adding two items are below:

On browse page
<img width="1442" alt="Screenshot 2024-09-10 at 6 06 37 PM" src="https://github.com/user-attachments/assets/d61e405a-aa63-4e12-941d-00206ac83626">

On widget in page, shows 6 items (after starting with 4 and then adding 2)
<img width="410" alt="Screenshot 2024-09-10 at 6 07 40 PM" src="https://github.com/user-attachments/assets/d7e1827d-a0a0-4948-a5c8-3e6fd19fd012">

**Comment by cbeer** [comment]
Is it possibly related to bulk tagging?

Reindex busts the exhibits cache with: https://github.com/projectblacklight/spotlight/blob/main/app/jobs/spotlight/reindex_job.rb#L20

But I don't see anything similar in `AddTagsJob`:
https://github.com/projectblacklight/spotlight/blob/main/app/jobs/spotlight/add_tags_job.rb

(I mean, it's also possible acts-as-taggable does it under the hood now :shrug:)

**Comment by taylor-steve** [comment]
Bulk tagging is a good thought. I tried a few variations during my attempt to recreate without any luck. I'm inclined to close this for now and re-open if it reoccurs. Any objections, or do folks feel this is serious enough to dig through previous versions to replicate/isolate the issue?
