### ISSUE TITLE
No choice of result page types in default application

### ISSUE THREAD

**Issue by mephillips-durham** [projectblacklight/spotlight#2993]
Most Spotlight production systems offer a choice of results page types such as list view, gallery, masonry etc. The [wiki implies that this is the default](https://github.com/projectblacklight/spotlight/wiki/Configuration-settings#results), and that users can also choose the number of results to show per page.

In a freshly-bootstrapped Spotlight application, without any configuration changes, the buttons to choose the number of results per page and the type of results page to use are not present. I have been unable to find any information on how to turn them on.

### Background investigations
On the Stanford Spotlight, the tools in question are part of the div with class sortAndPerPage, and more specifically, inside the div with class equal to search-widgets. The classes for the tools are per_page-dropdown and view-type.

In a freshly-made application, on the results page we have a div with class of sortAndPerPage but the search-widgets div only contains the "Save this search" and the "Bulk actions" buttons.

**Comment by corylown** [comment]
The `CatalogController` that is copied into the generated app is missing some of the configuration required to display the sort, per page, and result view options. These should be getting added by the Blacklight generator, but I think the spotlight template overwrites it. Adding the required configuration to the `CatalogController` template in Spotlight should fix this.

https://github.com/projectblacklight/spotlight/blob/main/lib/generators/spotlight/templates/catalog_controller.rb

```
    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)
```
