### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by whisere** [projectblacklight/spotlight#3008]
try export and import json:

no implicit conversion of Symbol into String:

    ```
def deserialize_featured_image(obj, method, data)
      file = data.**delete**(:image)
      image = obj.public_send("build_#{method}")
      image.update(data)
      if file
```

[Application Trace](http://localhost:3000/spotlight/test/import#) | [Framework Trace](http://localhost:3000/spotlight/test/import#) | [Full Trace](http://localhost:3000/spotlight/test/import#)
[spotlight (00789a235c38) app/services/spotlight/exhibit_import_export_service.rb:211:in `delete'](http://localhost:3000/spotlight/test/import#)
[spotlight (00789a235c38) app/services/spotlight/exhibit_import_export_service.rb:211:in `deserialize_featured_image'](http://localhost:3000/spotlight/test/import#)
[spotlight (00789a235c38) app/services/spotlight/exhibit_import_export_service.rb:181:in `block in from_hash!'](http://localhost:3000/spotlight/test/import#)
[spotlight (00789a235c38) app/services/spotlight/exhibit_import_export_service.rb:175:in `each'](http://localhost:3000/spotlight/test/import#)
[spotlight (00789a235c38) app/services/spotlight/exhibit_import_export_service.rb:175:in `from_hash!'](http://localhost:3000/spotlight/test/import#)
[spotlight (00789a235c38) app/models/spotlight/exhibit.rb:111:in `block in import'](http://localhost:3000/spotlight/test/import#)

**Comment by dnoneill** [comment]
@whisere could you give me more info on the steps you took to get this to error. I have tried multiple different import/export configurations and I haven't been able to get this error to show up.

**Comment by dnoneill** [comment]
@whisere I am going to close this issue on Wednesday Oct 23 if I don't hear from you.

**Comment by whisere** [comment]
Thanks @dnoneill , no problem, I think this has been resolved.

**Comment by dnoneill** [comment]
Thank you.
