### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/spotlight#3018]
Bootstrap 4 was EOL over a year and a half ago and is unsupported. https://getbootstrap.com/docs/4.6/end-of-life/

**Comment by corylown** [comment]
Bootstrap 4 to 5.3 migration guide: https://getbootstrap.com/docs/5.3/migration/

**Comment by corylown** [comment]
Looks like we might also need to update blacklight-gallery for Bootstrap 5 https://github.com/search?q=repo%3Aprojectblacklight%2Fblacklight-gallery%20data-slide&type=code

**Comment by corylown** [comment]
WIP for Spotlight: https://github.com/projectblacklight/spotlight/compare/main...bootstrap-5

Still to do:

- [ ] Commented out css needs review for updated bootstrap variables or different approach
- [ ] Carously related JS needs to work with both Bootstrap 4 or 5.
- [ ] Figure out what else I've missed causing bootstrap button/dropdowns not to work
- [ ] Style adjustments

**Comment by corylown** [comment]
Closed by https://github.com/projectblacklight/spotlight/pull/3075
