### ISSUE TITLE
Determine what is needed to support GA4 (Google Analytics 4)

### ISSUE THREAD

**Issue by corylown** [projectblacklight/spotlight#3050]
The previous version of Google Analytics (UA -- Universal Analytics) is no longer supported by Google. We should check whether the existing analytics code in Spotlight needs updating to work with GA4.

https://github.com/projectblacklight/spotlight/tree/main/app/models/spotlight/analytics

**Comment by dnoneill** [comment]
Looks like it might be possible with 

https://github.com/googleapis/google-cloud-ruby/tree/main/google-analytics-data
https://github.com/googleapis/google-auth-library-ruby
