### ISSUE TITLE
Investigate where tophat gem features are used

### ISSUE THREAD

**Issue by corylown** [projectblacklight/spotlight#3052]
Gem hasn't been updated in 7 years :https://github.com/stve/tophat
Can we remove it or replace it?

**Comment by corylown** [comment]
Looks like we're using this to add twitter and opengraph metatags, like:

```
<meta name="description" content="Martin Wong Catalogue Raisonné (MWCR) is an online, comprehensive compilation of finished artworks by Martin Wong." />
<meta name="twitter:card" value="summary" />
<meta name="twitter:url" value="https://exhibits.stanford.edu/martin-wong" />
<meta name="twitter:title" value="Martin Wong Catalogue Raisonné" />
<meta name="twitter:description" value="From the Martin Wong Foundation" />
<meta name="twitter:image" value="/images/9306-2a1cb57782fefab503b3d169328f869b/0,0,1012,1012/400,400/0/default.jpg" />

<meta property="og:title" content="Martin Wong Catalogue Raisonné" />
<meta property="og:image" content="/images/9306-2a1cb57782fefab503b3d169328f869b/0,0,1012,1012/400,400/0/default.jpg" />
<meta property="og:site_name" content="Spotlight at Stanford" />
```

Added in this commit: https://github.com/projectblacklight/spotlight/commit/fd111fd90d70a8bba8aba91e1c61c70d64a67173

Last release of the gem was in 2017: https://rubygems.org/gems/tophat/versions/2.3.1?locale=en

We're using this gem in a few other projects as well:

- purl
- library_hours_rails
- mise

**Comment by dnoneill** [comment]
@corylown I am looking into this as part of https://github.com/sul-dlss/exhibits/issues/2497. TopHat is malforming data. meta tags are supposed to have content="url/description/whatever the tag is". TopHat is putting it in value which is mal-forming. I am going to go ahead and start looking at how we might be able to replace this.
