### ISSUE TITLE
Bug:  ReferenceError: assignment to undeclared variable child_node

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/spotlight#3116]
### Description

When you try to nest feature page, there's a javascript error:

```
ReferenceError: assignment to undeclared variable child_node in updateWeightsAndRelationships
```

### Steps to reproduce

Go to the feature page admin (e.g. `http://127.0.0.1:3000/test-exhibit/feature`). Make two feature pages. Try to nest one under the other. See the javascript error, and see that saving changes doesn't.

### Expected behavior

It allows curators to nest pages.

**Comment by taylor-steve** [comment]
Might be worth checking if https://github.com/projectblacklight/spotlight/pull/3055 solves this problem, we need to move off of nestable anyway.
