### ISSUE TITLE
Feature: Add a "restore default" option for each metadata field in the Dashboard > Metadata section

### ISSUE THREAD

**Issue by marlo-longley** [projectblacklight/spotlight#3126]
This is based on https://github.com/sul-dlss/exhibits/issues/2486 -- we decided to propose the change upstream.

**Comment by marlo-longley** [comment]
I have the functionality working for this but I'd like some input on the design. It's a tight space with a lot going on. Obviously this placement of the button as seen below isn't great.

![Image](https://github.com/user-attachments/assets/301ed600-6892-4bfe-bb57-c0956be4d2ac)

Here is how the button looks in the existing Appearance section:
![Image](https://github.com/user-attachments/assets/94963e24-6f5d-4b85-b617-4decfaa432dd)

**Comment by marlo-longley** [comment]
WIP available in https://github.com/projectblacklight/spotlight/tree/restore-default-edit for safe keeping until further design decisions are made.

**Comment by alundgard** [comment]
Would it be possible to adjust the table header row font size and column width / padding to give more space to the Field name column? Here are some quick mockups.
<img width="830" alt="Screenshot 2024-09-18 at 11 39 14 AM" src="https://github.com/user-attachments/assets/e16966f5-2376-467a-8a27-bb07ce806b1b">
<img width="828" alt="Screenshot 2024-09-18 at 11 39 05 AM" src="https://github.com/user-attachments/assets/a859fe72-86e1-487f-922b-e09f0484ac12">

**Comment by marlo-longley** [comment]
@alundgard thank you! Nice I love the idea of compressing the columns. I will test it out.

**Comment by marlo-longley** [comment]
How's this looking to you @alundgard ? Thanks for your input.

<img width="1205" alt="Screenshot 2024-09-18 at 14 51 37" src="https://github.com/user-attachments/assets/70b8fe39-de28-4826-a309-2a1c2cb92730">

**Comment by alundgard** [comment]
That looks good to me @marlo-longley! I might suggest testing how it looks like when the **Field name** is very long—exceeding the available column space. Probably an unlikely case, but ideally the field name text would wrap to a second line, while the **Restore default** button stays where it is. (Note also: it looks like we're using sentence case for button text.)

**Comment by marlo-longley** [comment]
Thank you @alundgard.  I have the text wrapping to the second line and sentence case implemented below:

<img width="1205" alt="Screenshot 2024-09-18 at 16 34 17" src="https://github.com/user-attachments/assets/3a5d4378-d4c4-441d-9cab-2c40d995eb08">

The experience of entering a very label that exceeds the text input box is not good, but since that issue already exists in the current software, if we want to address it I think we should do it as a standalone issue. But I'm glad to have noticed that thanks to your testing suggestion.
 
<img width="1204" alt="Screenshot 2024-09-18 at 16 34 30" src="https://github.com/user-attachments/assets/1cd58d1e-0782-46a5-bd5c-e011394b0e69">

**Comment by alundgard** [comment]
Lgtm!
