### ISSUE TITLE
Bug: Viewer not displaying when item is being edited

### ISSUE THREAD

**Issue by corylown** [projectblacklight/spotlight#3155]
I think we lost the viewer here: https://github.com/projectblacklight/spotlight/pull/3148

I'd expect it to appear between the title and the  "Personal names" metadata.

<img width="1191" alt="Screenshot 2024-09-24 at 1 54 49 PM" src="https://github.com/user-attachments/assets/2a32787d-cfe4-43ad-94ae-e4e02a14333e">

**Comment by corylown** [comment]
@hudajkhan looks like it's a BL 7 vs 8 issues: The viewer is rendered with BL8 but not 7.

**Comment by hudajkhan** [comment]
@corylown do we want a solution that works with both, or will we just wait for BL8? thanks

**Comment by corylown** [comment]
both
