### ISSUE TITLE
Enable image area selection for non-Embed widgets

### ISSUE THREAD

**Issue by alundgard** [projectblacklight/spotlight#3186]
For widgets that display images statically (i.e., do not afford panning and zooming interactions within an embedded viewer).
- Item Row
- Uploaded Item Row
- Item Grid
- Item Carousel
- Item Slideshow

Add an option `Select image area` to specify the region of interest.
![image9](https://github.com/user-attachments/assets/2e194e12-fabd-49cd-a35f-150f7b3cc354)
Clicking `Select image area` opens a modal for the cropping interface. Repurpose the existing cropping interface and controls—currently used for the exhibit masthead and thumbnail images. However, unlike the masthead and thumbnail images, the blue area selector should be freeform rather than constrained to a fixed aspect ratio.
![image6](https://github.com/user-attachments/assets/424df437-4e04-4b0c-92e2-6f095329ff19)

**Comment by taylor-steve** [comment]
@alundgard and/or @hudajkhan I have a question about how the Item Grid widget should work with this. That widget imposes styling on the image to constrain them to the grid.  For example in #3350 if I configure a page as such:
![Screenshot 2024-12-16 at 3 22 23 PM](https://github.com/user-attachments/assets/3a93f4f7-9818-458e-b033-d83ee6490a52)
![Screenshot 2024-12-16 at 3 22 12 PM](https://github.com/user-attachments/assets/baf1207e-9e92-4700-8531-9a65ca0620da)

It yields:
![Screenshot 2024-12-16 at 3 22 36 PM](https://github.com/user-attachments/assets/1ff052c2-8100-4015-9ec9-32a07270b8fb)

Did this come up in discussion around this widget? In general, what are the expectations around widgets like this? E.g., do we keep the current styling or do we need to discuss how to alter the display side of the widget(s) to better reflect what this new feature offers?

**Comment by taylor-steve** [comment]
@alundgard That's perfect. I expected as much but I wanted to get it in the written history. Thanks!
