### ISSUE TITLE
Bug: this._map is null error from leaflet-iiif

### ISSUE THREAD

**Issue by taylor-steve** [projectblacklight/spotlight#3194]
### Description
When cropping an Exhibit's masthead there is an error `this._map is null` in the browser console from leaflet-iiif. This was seen in the `migrate-asset-pipeline` branch.

We need to know:
* Is this new behavior specific to the branch or is this an existing error?
* Is this error impacting functionality?
* If so, can we address this in Spotlight?

**Comment by corylown** [comment]
Not seeing this on spotlight main. And I'm not able to reproduce this on the `migrate-asset-pipeline` branch.

**Comment by taylor-steve** [comment]
Thanks for checking @corylown. I will double check on my end and close if I see the same.
