### ISSUE TITLE
Bug: Right chevron icon has incorrect color

### ISSUE THREAD

**Issue by taylor-steve** [projectblacklight/spotlight#3228]
### Description
This was seen on the `migrate-asset-pipeline` branch.

The right chevron for adding new feature pages and browse groups has switched from white to black.
![Screenshot 2024-10-21 at 1 36 42 PM](https://github.com/user-attachments/assets/d201b663-e4ce-4158-ad37-462dea4880c3)

### Steps to reproduce
* Go to Curation > Feature pages or Curation > Browse > Browse Groups

### Expected behavior
The icon fill color should match the text color (white).

**Comment by corylown** [comment]
Closed by #3238
