### ISSUE TITLE
Bug: Connection refused (redis://localhost:6379) when reindex

### ISSUE THREAD

**Issue by ta1986** [projectblacklight/spotlight#3325]
After upgrading Spotlight 3 to Spotlight 4, we are unable to reindex or add new items. Is Redis a new requirement of Spotlight 4?

![redis](https://github.com/user-attachments/assets/f3f7e431-f9d4-4f04-91ac-226e0fda8fdc)

**Comment by jcoyne** [comment]
It may be helpful to send the "Framework Trace", or the backtrace from you log file, otherwise we don't know what is causing this error.

**Comment by corylown** [comment]
@ta1986 can you check what you have configured as your production queue adapter? You should be able to find that in `config/environments/production`. If it's set to `config.active_job.queue_adapter = :sidekiq` then Sidekiq expects to connect to Redis.

**Comment by ta1986** [comment]
> It may be helpful to send the "Framework Trace", or the backtrace from you log file, otherwise we don't know what is causing this error. Redis is not a direct dependency of Spotlight, but you must have a Queuing Backend (https://github.com/projectblacklight/spotlight/wiki/Queueing-Backends) enabled. Some of these may use Redis.

Nothing shows up when I click on Full Trace / Framework Trace. Logs shows the same error.
We used Ruby 2.7 / Rails 5 for Spotlight 3. We switch to Ruby 3.3 / Rails 7 when upgrading to Spotlight 4.

`Started POST "/spotlight/mv/resources/reindex_all" for 130.14.233.116 at 2024-12-06 17:51:56 -0500
Cannot render console from 130.14.233.116! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Spotlight::ResourcesController#reindex_all as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "exhibit_id"=>"mv"}
  [1m[36mSpotlight::Exhibit Load (2.3ms)[0m  [1m[34mSELECT `spotlight_exhibits`.* FROM `spotlight_exhibits` WHERE `spotlight_exhibits`.`slug` = 'mv' LIMIT 1[0m
  [1m[36mUser Load (1.1ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 2 ORDER BY `users`.`id` ASC LIMIT 1[0m
  [1m[36mCACHE Spotlight::Exhibit Load (0.0ms)[0m  [1m[34mSELECT `spotlight_exhibits`.* FROM `spotlight_exhibits` WHERE `spotlight_exhibits`.`slug` = 'mv' LIMIT 1[0m
  [1m[36mSpotlight::Site Load (0.9ms)[0m  [1m[34mSELECT `spotlight_sites`.* FROM `spotlight_sites` ORDER BY `spotlight_sites`.`id` ASC LIMIT 1[0m
  [1m[36mSpotlight::Role Exists? (2.3ms)[0m  [1m[34mSELECT 1 AS one FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`role` = 'admin' AND `spotlight_roles`.`resource_type` = 'Spotlight::Site' AND `spotlight_roles`.`resource_id` = 1 LIMIT 1[0m
  [1m[36mSpotlight::Role Pluck (1.1ms)[0m  [1m[34mSELECT `spotlight_roles`.`resource_id` FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` != 'viewer' AND `spotlight_roles`.`role` = 'admin'[0m
  [1m[36mCACHE Spotlight::Role Pluck (0.0ms)[0m  [1m[34mSELECT `spotlight_roles`.`resource_id` FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` != 'viewer' AND `spotlight_roles`.`role` = 'admin'[0m
  [1m[36mCACHE Spotlight::Role Pluck (0.0ms)[0m  [1m[34mSELECT `spotlight_roles`.`resource_id` FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` != 'viewer' AND `spotlight_roles`.`role` = 'admin'[0m
  [1m[36mSpotlight::Role Exists? (2.2ms)[0m  [1m[34mSELECT 1 AS one FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` != 'viewer' LIMIT 1[0m
  [1m[36mSpotlight::Role Pluck (1.1ms)[0m  [1m[34mSELECT `spotlight_roles`.`resource_id` FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` != 'viewer'[0m
  [1m[36mCACHE Spotlight::Role Pluck (0.0ms)[0m  [1m[34mSELECT `spotlight_roles`.`resource_id` FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` != 'viewer'[0m
  [1m[36mCACHE Spotlight::Role Pluck (0.0ms)[0m  [1m[34mSELECT `spotlight_roles`.`resource_id` FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` != 'viewer'[0m
  [1m[36mCACHE Spotlight::Role Pluck (0.0ms)[0m  [1m[34mSELECT `spotlight_roles`.`resource_id` FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` != 'viewer'[0m
  [1m[36mSpotlight::Role Pluck (1.3ms)[0m  [1m[34mSELECT `spotlight_roles`.`resource_id` FROM `spotlight_roles` WHERE `spotlight_roles`.`user_id` = 2 AND `spotlight_roles`.`resource_type` = 'Spotlight::Exhibit' AND `spotlight_roles`.`role` = 'viewer'[0m
[ActiveJob] Failed enqueuing Spotlight::ReindexExhibitJob to Sidekiq(default): RedisClient::CannotConnectError (Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379))
Completed 500 Internal Server Error in 48ms (ActiveRecord: 12.3ms (14 queries, 6 cached) | GC: 2.2ms)


  
RedisClient::CannotConnectError (Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379)):

Causes:
Errno::ECONNREFUSED (Connection refused - connect(2) for 127.0.0.1:6379)`

**Comment by ta1986** [comment]
> @ta1986 can you check what you have configured as your production queue adapter? You should be able to find that in `config/environments/production.rb`. If it's set to `config.active_job.queue_adapter = :sidekiq` then Sidekiq expects to connect to Redis. But as mentioned above you can configure other adapters.

Interesting, I don't have that setting at all. There are 2 sample lines but both of them are commented out. What adapter do you recommend?
config.active_job.queue_adapter = :resque 
config.active_job.queue_name_prefix = "spotlight4_poc_2_production"

**Comment by corylown** [comment]
The backtrace you posted indicates that you have sidekiq configured as your queue adapter. It's possible this may be set in `config/application.rb` so you might check there. We use sidekiq (requiring redis). Is it possible you were using the `async` adapter in production previously? This would not require Redis but is not recommended by Rails for most production systems: https://edgeguides.rubyonrails.org/active_job_basics.html#job-execution

**Comment by ta1986** [comment]
Thanks @corylown, I found the setting in `config/application.rb`
`config.active_job.queue_adapter = ENV["RAILS_QUEUE"]&.to_sym || :sidekiq`

Yes, I used `async` in Spotlight 3. It was set in `config/cable.yml`. Sounds like I should install redis for Spotlight 4.
