### ISSUE TITLE
Selection scenario: Cross-institutional collaboration

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#509]
External feedback presents this scenario, likely to be of interest to other exhibit-builders:

> One question that’s come up has to do with external content. We have a faculty member currently collaborating with another institution on an online exhibition and would be interested in using content form both institutional repositories in one exhibition. While this may be achievable through content harvesting, will Spotlight have any functionality for pulling in external content?

**Comment by cbeer** [comment]
IIIF?
