### ISSUE TITLE
Admin/Curator documentation

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#537]
We need some documentation to help the admin/curator get started in exhibit-building and understand the various administration and curation features.

**Comment by randystern** [comment]
Could you point me to the doc please?

**Comment by jkeck** [comment]
Hi @randystern, we were cleaning up some issues, and perhaps confused this with a ticket describing local documentation.

There is some documentation in [our wiki](https://github.com/projectblacklight/spotlight/wiki/Configuration-settings) that could be useful, but certainly not comprehensive.

**Comment by caaster** [comment]
Hi @randystern -- here is our most recent curator-facing documentation (created in Dec 2016 by our Spotlight service team) for Stanford. This has been shared via the google blacklight list & also discussed briefly during the most recent Spotlight community call, in case it is helpful to others. Could be used as a framework/easily adaptable by other institutions using Spotlight. https://drive.google.com/open?id=0B8cF0k4YPwn6RW5FM3B4WDAxX2c

**Comment by randystern** [comment]
@caaster Thanks!

**Comment by mejackreed** [comment]
Based off of the convo here it looks like this is already done. Closing.

**Comment by caaster** [comment]
@randystern the most complete and up-to-date version of the above-mentioned documentation is now available on the Spotlight Community wiki: https://wiki.duraspace.org/display/SPOTLIGHT/Local+or+Internal+Documentation
