### ISSUE TITLE
Delete Contact email on Settings page

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#669]
We currently allow adding new contact email addresses on the Dashboard > Settings page, but there is no way for the Admin to remove a contact email address.

Need a way to delete an existing contact email address.

**Comment by caaster** [comment]
Jessie & I reviewed this ticket today, and decided it is straightforward & discrete enough to be placed into the ready column as is. Jessie recommends we propose a potential design for the fix, and run it by Gary when we're ready for a review.
